### ISSUE TITLE
[Outdated] webkit2gtk-unstable

### ISSUE THREAD

**Issue by Titaniumtown** [chaotic-aur/packages#1094]
## 👴 For reporting outdated packages

- Link to latest build: [here](https://builds.garudalinux.org/repos/chaotic-aur/logs/webkit2gtk-unstable.log)

- Package name: `webkit2gtk-unstable`

- Latest build: `2.33.1-1`

- Latest version available: `2.35.1-1`

- Have you tested if the latest version of the package builds in a clean chroot?:

  - [] YES
  - [X] NO

**Comment by dr460nf1r3** [comment]
There is an error which holds back the build since some time now, I also reported this around a month ago.  Seems to be an upstream issue to be me: `ninja: error: '/unstable/pointer-constraints/pointer-constraints-unstable-v1.xml', needed by 'WebKit2Gtk/DerivedSources/pointer-constraints-unstable-v1-protocol.c', missing and no known rule to make it`

**Comment by Technetium1** [comment]
@dr460nf1r3 that file is [here](https://cgit.freedesktop.org/wayland/wayland-protocols/tree/unstable/pointer-constraints/pointer-constraints-unstable-v1.xml). I get further in the build with `wayland-protocols` in depends, but I'm not sure if it should be in makedepends.

**Comment by Technetium1** [comment]
The reason it failed was that it used all the memory; causing it to be killed. Worked fine on `chaotic-dragon`, once it got the files from `wayland-protovols`.
```
real    68m33.644s
user    399m50.207s
sys     35m42.821s
```

**Comment by dr460nf1r3** [comment]
This is great news! So it was a missing dependency after all 👀
