### ISSUE TITLE
[Bug] kdenlive-git dependencies

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#1108]
## 🐛 For reporting bugs

- What happens?

When attempting an upgrade many Plasma packages conflict and request to be upgraded to the `-git` versions

- What is expected to happen?

I should be able to continue to use non `-git` packages as per https://aur.archlinux.org/packages/kdenlive-git/

- If possible, please attach logs.

Excerpt of some `-git` packages that shouldn't have wanted to switch:
```
attica-git-5.89.0_r847.g561512a-1-x86_64
breeze-icons-git-5.89.0_r1862.gaf3800ba-1-x86_64
chaotic-neofetch-git-7.1.0.r163.g7b1f0c27-2-any
cmake-git-3.22.0.520.g14f8990a60-1-x86_64
extra-cmake-modules-git-5.89.0_r3401.gb5684cb-1-x86_64
kaccounts-integration-git-20.12.0_r1233.g35c3442-1-x86_64
karchive-git-5.89.0_r521.g6bf564d-1-x86_64
kauth-git-5.89.0_r459.g0ccaa85-1-x86_64
kbookmarks-git-5.89.0_r437.gd88275d-1-x86_64
kcmutils-git-5.89.0_r574.gd82e565-1-x86_64
kcodecs-git-5.89.0_r399.g120e31a-1-x86_64
kcompletion-git-5.89.0_r471.g4015189-1-x86_64
kconfig-git-5.89.0_r897.g574508b9-1-x86_64
kconfigwidgets-git-5.89.0_r649.ge9296e0-1-x86_64
kcoreaddons-git-5.89.0_r1353.g4bb45c53-1-x86_64
kcrash-git-5.89.0_r422.g3fed76d-1-x86_64
kdbusaddons-git-5.89.0_r391.g49489c6-1-x86_64
kdeclarative-git-5.89.0_r949.gd97523f-1-x86_64
kded-git-5.89.0_r432.g794b9ed-1-x86_64
kdenlive-git-22.03.70.r15339-1-x86_64
kfilemetadata-git-5.89.0_r827.g75c565d-1-x86_64
kglobalaccel-git-5.89.0_r485.g9104503-1-x86_64
kguiaddons-git-5.89.0_r407.g6f85228-1-x86_64
ki18n-git-5.89.0_r523.gfab0f6f-1-x86_64
kiconthemes-git-5.89.0_r573.g4e48ca5-1-x86_64
kio-git-5.89.0_r5116.g66e8324b-1-x86_64
kirigami2-git-5.89.0_r2970.g652ba256-1-x86_64
kitemviews-git-5.89.0_r352.g8b3909b-1-x86_64
kjobwidgets-git-5.89.0_r391.ge5d1732-1-x86_64
knewstuff-git-5.89.0_r1241.g8dfde19f-1-x86_64
knotifications-git-5.89.0_r697.gdf26abf-1-x86_64
knotifyconfig-git-5.89.0_r363.ga7f5609-1-x86_64
kpackage-git-5.89.0_r713.gbdd5ea0-1-x86_64
kservice-git-5.89.0_r967.gb608d15-1-x86_64
ktextwidgets-git-5.89.0_r427.gb4aa1e2-1-x86_64
kwallet-git-5.89.0_r1102.ge9eb71b-1-x86_64
kwidgetsaddons-git-5.89.0_r895.g6bb4591e-1-x86_64
kwindowsystem-git-5.89.0_r642.ge895381-1-x86_64
kxmlgui-git-5.89.0_r827.g11c9cc80-1-x86_64
polkit-qt5-git-v0.114.0.r6.g96ee56a-1-x86_64
purpose-git-5.89.0_r917.g22a4a39-1-x86_64
signon-kwallet-extension-git-22.03.70_r66.g6412dd2-1-x86_64
solid-git-5.89.0_r729.gc44f590-1-x86_64
sonnet-git-5.89.0_r660.gc662d58-1-x86_64
syndication-git-5.89.0_r850.gccb1905-1-x86_64
```
Related commit: https://github.com/chaotic-aur/packages/commit/2cf1671468bee9278faf56941d07f6280e10e225

- My temporary solution

Replace `kdenlive-git` with `kdenlive`

**Comment by dr460nf1r3** [comment]
Hey there! In order to get our kf5/Plasma/KDE-git packages all to be built on latest packages only, we made the decision to also make `kdenlive-git` depend on those. As you might have noticed, its building from a PKGBUILD located in this group now rather than the AUR. 

I can offer you to build a package called `kdenlive-stabledeps-git` instead though 👀

**Comment by Technetium1** [comment]
That would explain it! I must admit it caused a small panic initially as I did have to ask for some help hunting down what may have caused the sudden pending changes. I've had to swap back from the `-git` packages in the past because of [these somewhat catastrophic failures](https://forum.manjaro.org/t/kate-dont-start-after-last-update/62950/26?page=2), so being able to avoid that would be ideal!

**Comment by dr460nf1r3** [comment]
Sure, Ill add them soon 😊

**Comment by ShayBox** [comment]
I used to like Chaotic, it was a great repository that provided binaries for AUR packages, but it's slowly been creating completely new, separate packages and not giving them a new name.  

When you create a new package but keep the old name it prevents anyone using chaotic from installing it, because if you install the aur package, when you go to update it will replace it with the chaotic package.

In this case, and every other case, the `chaotic/kdenlive-git` package should have remained a straight binary build of `aur/kdenlive-git`, and your new package that bases on git dependencies should have it's own name, as is the same with every other package similar.

I like Chaotic, but there's so many packages I have to keep update locked to prevent being replaced with package I didn't intend to use, and don't want to use that it's not worth using it all-together anymore.  

Every time I update there's a good chance you guys decided for me to replace a package with your own, without asking me, without telling me, it's a security risk at this point.

**Comment by dr460nf1r3** [comment]
In case of the kde-git packages you are right, there are a lot of packages not building directly from AUR. However this happens mostly because the PKGBUILDs in the AUR are outdated or not conforming with the rest of our packages. Personally, I wouldnt call having a list of curated packages a security risk - if thats your perception I'm sorry 👀

**Comment by Technetium1** [comment]
This is a valid solution and installed as expected, thank you.

**Comment by dr460nf1r3** [comment]
You are welcome. I noticed that for `kio-git` and `kdeclarative-git`, a lot of the dependencies are actually enforced at build time rather than via PKGBUILD which makes the idea of a `-stabledeps-git` package kinda redundant :/

**Comment by Technetium1** [comment]
It was more the intent originally for those packages which have dependencies that are now switched to `kio-git` and `kdeclarative-git` to also have the `-stabledeps-git` so that others can avoid having to upgrade and break system apps. I don't actually happen to use any other packages which have been affected by this change. I assumed that the creation of those new `-stabledeps-git` in https://github.com/chaotic-aur/packages/commit/d504c356b4ebdba3ef062ad2241b0bc8ca487081 was a part of the process of building any other related packages.
