### ISSUE TITLE
[Outdated] visual-studio-code-bin

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#1239]
### If available, link to the latest build

[visual-studio-code-bin.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/visual-studio-code-bin.log)

### Package name

`visual-studio-code-bin`

### Latest build

`1.64.1-1`

### Latest version available

`1.64.2-1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by coxackie** [comment]
This package has failed to build automatically 3 times in a row now... :(

**Comment by dr460nf1r3** [comment]
There is an ongoing issue with the `garuda-cluster` currently, it's not building hourly automatically for a yet unknown reason.. starting the routine manually builds all packages just fine. Thanks for both of you guys reports and patience, I'm trying to rebuild everything manually until we find the root cause for this behaviour!
