### ISSUE TITLE
[Request] Gazebo (one of ROS dependency)

### ISSUE THREAD

**Issue by 123-123-nil** [chaotic-aur/packages#1308]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/gazebo

### Utility this package has for you

I need [ros-noetic-desktop-full](https://aur.archlinux.org/packages/ros-noetic-desktop-full) for college. Gazebo is one of its dependency. I am unable to build gazebo as it requires a lot of ram(I was unable to perform a single threaded compile without -pipe flag with 16 GB of ram). Providing, this will make life of people who try to use ros-noetic or gazebo itself easier.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

The package seems to have issues with ffmpeg 5. So one will have to wait till its devs patches the package.https://github.com/osrf/gazebo/issues/3180

**Comment by sgse** [comment]
Can't build on my PC.
Which is not to say anything, I'm a beginner :-)
yay -S gazebo
~~~
==> Create package: ignition-fuel_tools-4 4.4.0-1 (Thu 03 Mar 2022 17:00:18 CET)
==> Check runtime dependencies...
==> Missing dependencies:
  -> ignition-common-3
==> Check buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
Error: unable to build 'ignition-fuel_tools-4-4.4.0-1': 
==> Build package: gazebo 11.9.1-1 (Thu 03 Mar 2022 17:00:19 CET)
==> Receive sources...
  -> Download gazebo-11.9.1.tar.bz2...
  % Total % Received % Xferd Average Speed Time Time Current
                                 Dload Upload Total Spent Left Speed
100 53.8M 100 53.8M 0 0 2536k 0 0:00:21 0:00:21 --:--:-- 3648k
  -> fix-for-tbb-2021.patch found
==> Check source files with sha256sums...
    gazebo-11.9.1.tar.bz2 ... Success
    fix-for-tbb-2021.patch ... Success
==> Create package: gazebo 11.9.1-1 (Thu 03 Mar 2022 17:00:42 CET)
==> Check runtime dependencies...
==> Missing dependencies:
  -> ignition-common-3
  -> ignition-fuel_tools-4
==> Check buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
Error: can't build 'gazebo-11.9.1-1': 
Error: can't build packages: ignition-common-3-3.14.0-1 ignition-fuel_tools-4-4.4.0-1 gazebo-11.9.1-1
~~~
same on chaotic
~~~
warning: curl-7.81.0-3 is up to date -- skipping
error: target not found: libccd
warning: libtool-2.4.6+59+gb55b1cc8-2 is up to date -- skipping
warning: libxml2-2.9.13-1 is up to date -- skipping
error: target not found: ogre-1.9
error: target not found: sdformat-9
error: target not found: ignition-math>=6
error: target not found: ignition-transport-8
error: target not found: ignition-cmake>=2
error: target not found: ignition-common-3
error: target not found: ignition-fuel_tools-4
error: target not found: ignition-msgs-5
Container pkgce964fe7442 failed with error code 123.

umount: /root/gazebo/machine/root/home/main-builder/pkgwork unmounted
umount: /root/gazebo/machine/root/home/main-builder/.ccache unmounted
umount: /root/gazebo/machine/root/home/main-builder/pkgsrc unmounted
umount: /root/gazebo/machine/root/var/cache/pacman/pkg unmounted
umount: /root/gazebo/machine/root/var/pkgdest unmounted
umount: /root/gazebo/machine/root (overlay) unmounted
~~~

**Comment by dr460nf1r3** [comment]
Try `chaotic get -r gazebo`, then `chaotic mkd lastpackage packagebeforelastone` and so on. The dependencies are likely in AUR and need to be built before the actual package.

**Comment by 0ljik** [comment]
ogre-1.10 -> 1.12 doesn't build on arch. ignition rendering 6.0.1 builds with ogre-1.9. 
ignition-common needs to be build from git because of ffmpeg5, and gazebo also has to be guild from git with unmerged PR for fixing ffmpeg5. Building gazebo required ~55GB of RAM.

**Comment by dr460nf1r3** [comment]
That explains why I had difficulties building this.. :/

**Comment by 0ljik** [comment]
probably ros-noetic-gazebo-ros also requires 50GB RAM to build. This package is also required for connecting ROS with gazebo.
I have built galactic version from git. CMakeFiles in test for gazebo_ros and gazebo_plugins required linking tbb library to successfully build.

**Comment by acxz** [comment]
`ros-noetic-gazebo-ros` does not require that much RAM, it's only `gazebo` which it depends on. Note, that the build RAM usage can be decreased by lowering the amount of cores used.

**Comment by acxz** [comment]
> Can't build on my PC.
Which is not to say anything, I'm a beginner :-)
yay -S gazebo

Weird, in my experience `yay` has the best dependency resolution out of all the existing AUR helpers, including `paru`.

> ogre-1.10 -> 1.12 doesn't build on arch.

`gazebo` does not work with `ogre>1.9` only `ogre=1.9`.

> ignition rendering 6.0.1 builds with ogre-1.9.

`gazebo` does not require `ignition-rendering`

> ignition-common needs to be build from git because of ffmpeg5,

To be specific here, `ignition-common-3` is required to build `gazebo`. `ignition-common-3` does not require `ffmpeg5` but it uses the older compat package `ffmpeg4.4`.

> and gazebo also has to be build from git with unmerged PR for fixing ffmpeg5.

`gazebo` builds in a clean chroot just fine for me, without installing `git` or patching the package. If you could post a build/error log over at https://aur.archlinux.org/packages/gazebo, we could help you any issues you might be facing. (Maybe `gazebo` should add an explicit dep on `ffmpeg4.4` instead of just using `ffmepg`).

**Comment by 0ljik** [comment]
> > ogre-1.10 -> 1.12 doesn't build on arch.
> 
> `gazebo` does not work with `ogre>1.9` only `ogre=1.9`.
> 
> > ignition rendering 6.0.1 builds with ogre-1.9.
> 
> `gazebo` does not require `ignition-rendering`
> 

sorry, I was mistaken for other package that required ignition-rendering

> > ignition-common needs to be build from git because of ffmpeg5,
> 
> To be specific here, `ignition-common-3` is required to build `gazebo`. `ignition-common-3` does not require `ffmpeg5` but it uses the older compat package `ffmpeg4.4`.
> 
> > and gazebo also has to be build from git with unmerged PR for fixing ffmpeg5.
> 
> `gazebo` builds in a clean chroot just fine for me, without installing `git` or patching the package. If you could post a build/error log over at https://aur.archlinux.org/packages/gazebo, we could help you any issues you might be facing. (Maybe `gazebo` should add an explicit dep on `ffmpeg4.4` instead of just using `ffmepg`).

that's for you to decide which one do you want to use. I tend to go with arch version rather than old compat versions from aur.
I don't have any issues. All I wanted to was to give information what I had. I am already running sims and full ROS system with all dependencies for my project.

**Comment by acxz** [comment]
> that's for you to decide which one do you want to use.

unless you are modifying the PKGBUILD, the deps will be pulled in automatically which specifically state [ffmpeg4.4](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ignition-common-3#n11)

Saying that it *needs* to be built from git because of ffmpeg5 is an incorrect statement. The package does not need any modifications to be built on Chaotic-AUR and this FR shouldn't be held up because of that.

> I tend to go with arch version rather than old compat versions from aur.

I assume by arch version you mean the packages available in the official repos. ([core]/[extra]/[community]). ffmpeg4.4 is also available in [extra] and is not in the aur.

**Comment by Technetium1** [comment]
Supposedly the issue was fixed in https://github.com/osrf/gazebo/pull/3195

**Comment by xiota** [comment]
`gazebo` and related packages are broken and look complicated to fix.  Metrics show 0 downloads.  I plan to drop if there are no objections.

**Comment by xiota** [comment]
Dependencies are also dropped.  If any are still needed, feel free to open new requests.
