### ISSUE TITLE
[Request] Realvnc Server

### ISSUE THREAD

**Issue by Bhooty** [chaotic-aur/packages#1351]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/realvnc-vnc-server

### Utility this package has for you

I use it to access the pc locally

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Interestingly this brought up another issue... The build succeeds but is not able to be saved due to lack of free space.
> `Write failed: No space left on device`

Full log: https://bin.garudalinux.org/?cbcb46131667bb66#HxoFPTRvHC3Y8ChHkexekTu2WGDCbVLF4PRgteyfXDRp
Partial log: https://builds.garudalinux.org/repos/chaotic-aur/logs/realvnc-vnc-server.log

**Comment by Technetium1** [comment]
Update: /tmp just ran out of space and `@JustTNE` dealt with it.
