### ISSUE TITLE
[Bug] Freetube Crashes on launch

### ISSUE THREAD

**Issue by toddzilla57** [chaotic-aur/packages#1376]
### What happens?

Due to `electron` updating to v18, Freetube no longer opens. This can be fixed by replacing `electron` with `electron17` in both dependencies, and in `freetube.sh` : `exec electron17 /usr/lib/freetube/app.asar "$@"`

Freetube devs officially support `electron16`, however I have tested with `electron17` and everything works fine as far as I can tell.

### What is expected to happen?

Freetube opens when launched

**Comment by Technetium1** [comment]
Related https://github.com/FreeTubeApp/FreeTube/issues/2190

**Comment by absidue** [comment]
The FreeTube issue about this issue specifically: https://github.com/FreeTubeApp/FreeTube/issues/2163

**Comment by absidue** [comment]
I see you added the waiting for upstream-fix label. I don't use the AUR or any operating system that uses it, however as far as I can tell from people reporting the issue you are currently providing an unuable package due to the incorrect dependency. I recommend fixing the dependency issue on your side instead of waiting for an update on the upstream side, so that you can at least provide a usuable package for your users.

**Comment by dr460nf1r3** [comment]
That's a good point, I removed it for the time being. 
It still needs to be commented out from the routine as I don't have access to my work device right now.

**Comment by dr460nf1r3** [comment]
Just confirmed this fixed! 🥳

**Comment by Technetium1** [comment]
Oops I forgot to close this one too, confirmed fix!

**Comment by toddzilla57** [comment]
Thanks! Great work guys!
