### ISSUE TITLE
[Request] whatsapp-for-linux

### ISSUE THREAD

**Issue by DenjixPochita** [chaotic-aur/packages#1386]
### Link to the package(s) in the AUR

[whatsapp-for-linux](https://aur.archlinux.org/packages/whatsapp-for-linux)

### Utility this package has for you

Webkit based whatsapp client

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropped because removed from AUR following rebrand to wasistlos.  Not switching packages because aurweb comments indicate it's not working.  Last release was Oct 2024.

If someone wants the new package, please open a new request after there's a new release and evidence that it is functional.

Metrics 717.
