### ISSUE TITLE
[Outdated] wine-wl-git

### ISSUE THREAD

**Issue by abrattic** [chaotic-aur/packages#1478]
### If available, link to the latest build

[wine-wl-git]https://builds.garudalinux.org/repos/chaotic-aur/logs/wine-wl-git.log

### Package name

wine-wl-git

### Latest build

6.0rc1.r13643.gf6f79416b81-1

### Latest version available

7.10

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

It looks like the package was built by chaotic-AUR recently, but when I run `wine --version` it gives me `6.0rc1.r13643.gf6f79416b81-1`.

**Comment by dr460nf1r3** [comment]
This is a pretty weird issue - I had a look at the PKGBUILD, and it seems to build from the correct branch while `pkgver` reports the wrong value. Seems like the maintainer hasn't figured it out either 🤔

**Comment by dr460nf1r3** [comment]
The maintainer has [answered](https://aur.archlinux.org/packages/wine-wl-git#comment-868341) my question:

> @dr460nf1r3 The git repository left the Git tag at the version they forked it and haven't updated the tag since then.
> 
> What you see is the git tag. But the version is on the version file in the repository. I myself tend to read the activity tab on the git repository, thus I follow the updates and such. But to answer your question, it's a newer 7.0 version and not the 6.0 branch.

So basically the versions don't reflect the actual branch it builds from (which was my own impression while investigating the PKGBUILD as well), the actual content is from recent commits though. Since the it the PKGBUILD behaves like that and there is no obvious bug during running the build, I'm going to close the issue :)

**Comment by semka95** [comment]
Hello, package maintainer here. Repository owner is not creating new tags on every new version, so I decided to update package, now it parses version from `VERSION` file, not from tags. Sorry for the inconvenience.

**Comment by dr460nf1r3** [comment]
Very nice addition, thanks for letting us know over here! :)
