### ISSUE TITLE
[Request] lutris-wine-git

### ISSUE THREAD

**Issue by niizam** [chaotic-aur/packages#1666]
### Link to the package(s) in the AUR

[lutris-wine-git](https://aur.archlinux.org/packages/lutris-wine-git)
and it's dependencies
[xkb-switch](https://aur.archlinux.org/packages/xkb-switch)
[latencyflex-git](https://aur.archlinux.org/packages/latencyflex-git)
[libstrangle-git](https://aur.archlinux.org/packages/libstrangle-git)

### Utility this package has for you

This Wine/Proton wrapper make Windows applications and games more easy to launch.
You can just click the `.exe` and it will run with any Wine/Proton version as you want.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

`lutris-wine-git` require `latencyflex-git`, `xkb-switch`, and `libstrangle-git` as it's dependencies.
Thank you.

**Comment by Technetium1** [comment]
Ordered:
```
mangohud
vkbasalt
xkb-switch
lib32-mangohud
lib32-vkbasalt
libstrangle-git
latencyflex-git
lutris-wine-git
```

**Comment by xiota** [comment]
Will be removing `lutris-wine-git` and its dependencies because:

* Package is broken.  Previous build can no longer be installed and used.
* Upstream has dependency issues that are unlikely to be resolved any time soon.
* Lutris developer @strycore has [advised](https://aur.archlinux.org/packages/lutris-wine-git#comment-917005) against using this package because it unrelated to the Lutris Project, despite the name.
