### ISSUE TITLE
[Request] lens

### ISSUE THREAD

**Issue by micw** [chaotic-aur/packages#1673]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/lens

### Utility this package has for you

Lens is a UI for kubernetes. There are 2 versions. A commercial one whihc requires an account that is already in chaotic aur under the name "lens-bin" and a OSS version "openlens" that is available under the name "lens".

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
@micw do you mean to request [openlens-bin](https://aur.archlinux.org/packages/openlens-bin), since as mentioned, `lens` is already in Chaotic?

**Comment by micw** [comment]
Nope.

If you download lens from the vendor, you get the commercial version ("lens-bin") - this one is in chaotic aur.

If you pull from the official git and build it, you get the open source version. This one is in aur as "lens" but not in chaotic aur.

Openlens-bin is a 3rd party build of lens from git. It is an open source drop-in replacement for the vendor's binaries.

I think it's better to use "lens" (without -bin) rather than openlens-bin.

**Comment by xiota** [comment]
Dropping because this depends on non-existent package.

**Comment by micw** [comment]
@xiota Just saw that the package was dropped. What is the exact reason?

**Comment by Technetium1** [comment]
@micw [upstream went closed source](https://github.com/lensapp/lens#history-of-this-repository), so this package is now useless😢... [nodejs-lts-gallium](https://aur.archlinux.org/packages/nodejs-lts-gallium) was previously deleted, but is now back, and needs updated. Even once it's updated we will not provide this version due to the source version being killed off. Upstream will distribute a binary version, and `lens-bin` (https://github.com/chaotic-aur/packages/issues/1658) is just an [appimage that isn't worth providing](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lens-bin#n18), and also doesn't have the correct license after source changed.

Further, [`openlens`](https://aur.archlinux.org/packages/openlens-bin) has been abandoned too. It's very unfortunatly time to look at alternatives. See also https://github.com/lensapp/lens/issues/5444#issuecomment-1137271180
