### ISSUE TITLE
[Request] TROMjaro's library part 1

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1693]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/corepdf + https://aur.archlinux.org/packages/corepdf-git
https://aur.archlinux.org/packages/metronome + https://aur.archlinux.org/packages/metronome-git
https://aur.archlinux.org/packages/health
https://aur.archlinux.org/packages/image-roll-bin
https://aur.archlinux.org/packages/corekeyboard
https://aur.archlinux.org/packages/g4music + https://aur.archlinux.org/packages/g4music-git
https://aur.archlinux.org/packages/gis-weather + https://aur.archlinux.org/packages/gis-weather-git
https://aur.archlinux.org/packages/revelation

### Utility this package has for you

These are some of the packages we test for months for our TROMjaro library at https://www.tromjaro.com/apps/. We have a custom Linux Distro and recently working to integrate the Chaotic AUR. 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

We would love to share more and more AUR packages that we have tested over the past 2 or so years of that's not too much. Let me know if we should submit more and more packages from our library. And thank you for your work!

**Comment by dr460nf1r3** [comment]
Hey! It's cool to see distributions adopt Chaotic-AUR :) What kind of packages do you test mostly? :eyes:

**Comment by tio-trom** [comment]
> Hey! It's cool to see distributions adopt Chaotic-AUR :) What kind of packages do you test mostly? eyes

We have our own criteria that we call [trade-free](https://www.trade-free.org/). Meaning you should not trade anything to this app in order to use it. Not your data (so no data collection allwoed), not your currency (so no freemium apps with trial modes or "pro" features), not your attention (so no ads inside apps). Also do not trade your freedom (so you should be allowed to modify the source code and share it - what would go under "open source" licenses). We can't be that exact with our testing and categorizing. But in essence we test a lot of apps and only those that are good quality and "trade-free" would go to our library.

These "apps" from our library are quite useful and no BS as I said, like data collection, freemiums, ads and so forth.

If it is ok with you guys we can submit a  bunch here, a few at a time or how you prefer.

**Comment by Technetium1** [comment]
@tio-trom Feel free to submit a bunch of requests at your leisure! It's often easier to handle grouped packages together, that way if one thing fails to build it doesn't hold up closing the issue altogether. Otherwise, if they are not directly tied together it can take a while. For example, notice that we can't close this one yet because one of the dependencies doesn't build, causing cascading failure of half of the requests: https://github.com/chaotic-aur/packages/issues/1672

**Comment by tio-trom** [comment]
Ok so to make sure I got your right, is it better to submit a bunch of packages into one rather than submitting individual packages? I do not want to spam you people since we have a big list of packages. And I love that you guys are doing this!

**Comment by Technetium1** [comment]
@tio-trom We only build pkgbases, so if you can request and link to pkgbase where applicable, that is helpful. We recursively get the dependencies that are only on the AUR for those pkgbases. I use [aurutils](https://github.com/AladW/aurutils) with this alias to find dependencies: `alias aurdeps='aur depends --pkgbase '`

Yes, it is preferred to have many smaller requests if the pkgbases are different or unrelated. Some bigger when the packages are related, for example https://github.com/chaotic-aur/packages/issues/1682 is going to be **ALL** the KCM modules on the AUR, it makes sense for it to be big, because there are many pkgbases to add.

**Comment by tio-trom** [comment]
Ok we will do that. Hopefully we won't overwhelm you. We will try to limit ourselves to a bunch of submissions a day, for the packages that we consider more important and we have tested a lot.

**Comment by Technetium1** [comment]
> Hopefully we won't overwhelm you

Don't worry, you won't!

> We will try to limit ourselves to a bunch of submissions a day

There's not really a limit to requests, as long as you're following the guidelines and the packages provide value.

**Comment by Technetium1** [comment]
- [ ] corepdf
- [ ] corepdf-git
- [ ] metronome
- [ ] metronome-git
- [ ] health
- [ ] image-roll-bin
- [ ] corekeyboard
- [ ] g4music
- [ ] g4music-git
- [ ] gis-weather
- [ ] gis-weather-git
- [ ] revelation

**Comment by Technetium1** [comment]
`gis-weather-git` has an incorrect URL, otherwise built fine in a clean chroot locally. I'm going to flag the package.

```diff
-source=("${pkgname}::git://github.com/RingOV/gis-weather")
+source=("${pkgname}::git+https://github.com/RingOV/gis-weather")
```

**Comment by tio-trom** [comment]
Oh ok thank you!

**Comment by Technetium1** [comment]
@librewish was there any particular reason you dropped [corepdf-git](https://aur.archlinux.org/packages/corepdf-git) and [libcprime-git](https://aur.archlinux.org/packages/libcprime-git)?

**Comment by Technetium1** [comment]
@tio-trom I'm declining `corepdf-git` because `libcprime-git` is an orphan.

**Comment by tio-trom** [comment]
I see https://aur.archlinux.org/packages/health was dropped?

**Comment by xiota** [comment]
Original request had both `metronome` and `metronome-git`.

`metronome-git` was dropped because it was broken.  However, they are very different packages.  One is a music pacing program `metronome`.  The other is related to xmpp chat protocol.  Given the confusing naming, were they both intended?  If not, which one was actually wanted?

**Comment by xiota** [comment]
> I see https://aur.archlinux.org/packages/health was dropped?

```
$ pacman -Ss health | grep chaotic-aur
chaotic-aur/health 0.94.0-4
```
