### ISSUE TITLE
[Request] vdhcoapp-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1706]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/vdhcoapp

### Utility this package has for you

Together with the Download Helper browser extension it allows anyone to download media from websites. Very useful!

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Requesting removal because the binary built from this package doesn't work (with Firefox).   There appears to be some issue with npm modules.  Package maintainer has not addressed or responded to any issues raised in comments.  Upstream has not been updated in over a year, and developer appears to have been mostly inactive for two years.

**Comment by Technetium1** [comment]
Good reasons.

**Comment by xiota** [comment]
I just created [`vdhcoapp-git`](https://aur.archlinux.org/packages/vdhcoapp-git).  The commits after the 1.6.3 appear to be inconsequential, but took it as an excuse to make a new package since the maintainers for `vdhcoapp` seem to have gone MIA.

The new package applies changes from https://github.com/mi-g/vdhcoapp/pull/149 which seem to fix build issues.  Built in a clean chroot and tested by downloading a short YouTube clip.

**Comment by xiota** [comment]
Pausing rebuilds in 226385bf5480f1256c39294a8ed909a1e20c7b20 because npm incompatibilities seem to be causing non-working binaries.  Looks similar to what happened before.  Same thing seems to happen with `vdhcoapp`.    As far as I can tell, the last successful build in the repository still works.

Upstream has resumed development, and seems to have changed the build process.  Once they produce a real release, maybe someone can figure out how to build it.

**Comment by xiota** [comment]
Leaving `vdhcoapp`/`-git` packages paused at 1.6.3.  The 2.0.x releases do not appear to be viable.  The repo build script does not work on Arch, and the Firefox extension does not recognize the new upstream binaries, installed with `aur/vdhcoapp-bin`.

**Comment by xiota** [comment]
Dropping because the browser extension (as of version 10.x) no longer uses the helper app.

Metrics:

* vdhcoapp # 27
* vdhcoapp-git # 5
