### ISSUE TITLE
[Request] basket + basket-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1734]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/basket-git
https://aur.archlinux.org/packages/basket

### Utility this package has for you

All-purpose notes taker

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because project looks abandoned.  Last release was a beta, years ago, after which development ceased.  Recent commits are automated housekeeping.

git package is poorly maintained with incorrect depends.  stable package was disowned by its long-time maintainer.

Usage has been declining: [pkgstats/basket](https://pkgstats.archlinux.de/packages/basket), [pkgstats/basket-git](https://pkgstats.archlinux.de/packages/basket-git)
