### ISSUE TITLE
[Remove] tauon-music-box

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1833]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/tauon-music-box

### Utility this package has for you

A modern streamlined music player

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by tio-trom** [comment]
I see it fails to build because of dependency issues.

```
error: target not found: python-pysdl2
error: target not found: python-isounidecode
```

https://builds.garudalinux.org/repos/chaotic-aur/logs/filtered/dep-not-in-repo/tauon-music-box.log

**Comment by dr460nf1r3** [comment]
https://github.com/chaotic-aur/packages/issues/2086

**Comment by Technetium1** [comment]
Done

**Comment by xiota** [comment]
Dropped because moved to extra.  Metrics 266.

**Comment by miloumeeloo** [comment]
Could you please keep this package alive ? On manjaro, it's a mess to install from extra due to python version still in 3.13.

**Comment by xiota** [comment]
@miloumeeloo You can keep the old package installed while waiting for Manjaro to update (typically ~2 weeks).  Re-adding this package wouldn't help you because Chaotic AUR attempts to stay synced with vanilla Arch.  Nearly all relevant packages have already been rebuilt for Python 3.14.  I recommend Manjaro users [switch to the testing branch](https://wiki.manjaro.org/index.php/Switching_Branches) when using Chaotic AUR.
