### ISSUE TITLE
[Request] pixelorama + pixelorama-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1864]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/pixelorama-git
https://aur.archlinux.org/packages/pixelorama

### Utility this package has for you

A free & open-source 2D sprite editor

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
I'm dropping these packages.  Would be reasonable to add the `bin` package instead. (#2822)

The git package isn't building because of an incorrect command-line option.  I commented two weeks ago, and the maintainer replied with the correct option, but has yet to actually fix the package.

With the correct option, both the stable and git packages "successfully" build packages, but show lots of errors along the way.  I have no idea if that's normal.  The git package looks like it "works".  The stable package has glitchy/corrupt-looking graphics.

Both packages download a nearly 1GB file in the `prepare()` function.  Since it's not in `source`, the file is not cached.  Since `prepare()` is run before `pkgver()` and the version check, when the packages are rebuilt every hour, the files are redownloaded, even if the subsequent version check determines no build is necessary.  So around 45GB are thrown away every day on these two broken packages.  Each month, 1.35TB.  Since they were added, 18TB.
