### ISSUE TITLE
[Request] Moebius

### ISSUE THREAD

**Issue by Paulie420** [chaotic-aur/packages#1923]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/moebius

### Utility this package has for you

Moebius is an ANSI editor for current OSes. Remember using TheDraw back in the DOS days? Moebius brings ANSI art (https://16colo.rs/) current day editors. 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Again, this would make a great AppImage and thats why I'm requesting Moebius to be added... thanks and I hope you think its worthy, too. :P

**Comment by Technetium1** [comment]
Thanks for the request, unfortuneately we have decided that it's not a great idea to add this, based on the fact that it's relying on Electron version 9, which has been [end of life since 18 May 2020](https://endoflife.date/electron). There are scenarios where it's unavoidable and acceptable to use an older version, but it doesn't sit well with me that this runs a _server_ which inherently relies on vulnerable & unsupported software.

> this would make a great AppImage and thats why I'm requesting Moebius to be added

We don't actually have anything to do with building AppImages, so that would be out of scope.

Please feel free to request this again when it's using a more recent version of Electron!
