### ISSUE TITLE
[Request] gradience-plugins & gradience-git

### ISSUE THREAD

**Issue by 0xMRTT** [chaotic-aur/packages#1942]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/gradience-git
https://aur.archlinux.org/packages/gradience

### Utility this package has for you

Customizing GNOME and libadwaita with ease

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
`gradience` added in https://github.com/chaotic-aur/packages/commit/8219f5b5ab3e30f645eb5ceac0843990e730c9d8 for #1941

**Comment by Technetium1** [comment]
I don't know why we don't have [gradience-plugins](https://aur.archlinux.org/packages/gradience-plugins) as well…

**Comment by 0xMRTT** [comment]
Oh, sorry it was just gradience and gradience-git.

**Comment by Technetium1** [comment]
@0xMRTT I know. What I _should_ have done is closed https://github.com/chaotic-aur/packages/issues/1941 and went with this, since it adds in `gradience-git` here but not the other. However, I saw that other first since it was older. That's why it was added in such a bad way.

I changed the links and title on purpose, so that I can add on `gradience-plugins` to `gradience-git`, and complete adding all of `gradience-*` packages. The reason for the title change is VERY intentional, please don't change it back. It's so that I (and requesters) can look up duplicate packages and previous denials, so something doesn't end up double-requested. :)

**Comment by xiota** [comment]
Dropping because incompatible with Python 3.12.
