### ISSUE TITLE
[Request/Outdated/Meta] Rebuild all package in kde-git-meta + prepare for qt6 KDE

### ISSUE THREAD

**Issue by Nyabinary** [chaotic-aur/packages#2014]
### Package name

kde-git-meta (and all packages in it + discover-git)

### Latest build

commit vers

### Latest version available

master

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

A lot of packages in kde git meta are not building correctly to their latest commits as well as discover-git not building to the latest commit.

**Comment by VexfulNiko** [comment]
KDE Plasma 5.27 is planning to be the last Qt5 release. Considering this is a git package we're probably going get the first signs of that in February (after Plasma 5.27 is release or even before February) so we should prepare for that including having the qt6 group in git packages as well.
https://www.phoronix.com/news/Plasma-5.27-Last-5-Release
Cc @dr460nf1r3 @Technetium1 @alexjp

**Comment by alexjp** [comment]
I am already rebuilding the kde-git routines... kf5 and plasma5 should be done, now kde apps.

I will monitor today to see if everything is OK. ( this was stopped because the builders were **improved** :P )

In terms of the future, I have some ideas on how to go on with this, and will discuss it to see if its possible. Seeing that, git packages are actually very stable for day to day usage (and if not, its easy with btrfs snapshots to revert), I would like to improve how they are being done now.

Also I would like to make it easy to switch between stable and git package. ( in case some problem and user doesn't use btrfs or btrfs snapshots, easy to revert to stable packages ).

**Comment by Technetium1** [comment]
Create a `-git` version of [base-devel-meta](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=base-devel-meta)?

**Comment by VexfulNiko** [comment]
Yep practically

**Comment by VexfulNiko** [comment]
@alexjp What are your ideas for QT6 and making sure the git pkgs are compatible with QT6? Dependencies have to be upgraded also. I would create a qt6-base-git version to accompany the KDE pkgs.

**Comment by alexjp** [comment]
> @alexjp What are your ideas for QT6 and making sure the git pkgs are compatible with QT6? Dependencies have to be upgraded also. I would create a qt6-base-git version to accompany the KDE pkgs.

I will discuss this on the weekend with the builders mantainers, to see what is possible to do.

About qt6 in git, i am not thinking about it, to keep the possibility of using just kde/plasma/kde-apps git, but not have qt6 git break anything outside of KDE.

Anyway, whatever will be discussed and settled, i will report it here! ( or, if you wanna help :P join at the chaotic-aur telegram :P )

**Comment by VexfulNiko** [comment]
I would like to see qt6 git as well tbh but optional.

**Comment by Technetium1** [comment]
Superseded by #2279
