### ISSUE TITLE
[Request] ruffle-nightly-bin, exodus, flashplugin

### ISSUE THREAD

**Issue by completelygenericusername** [chaotic-aur/packages#2020]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/ruffle-nightly-bin
https://aur.archlinux.org/packages/exodus
https://aur.archlinux.org/pkgbase/flashplugin

### Utility this package has for you

ruffle lets you play flash games from .swf files, exodus is a multi-crypto wallet, and pepper-flash is required for some streaming services to work on qtwebflix

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
We already have exodus :smiley:

**Comment by completelygenericusername** [comment]
you do? when i `yay exodus` i only see the following:
![image](https://user-images.githubusercontent.com/109995907/194967371-f2105246-cf7d-44f9-83ca-5682d1e7b5c5.png)

**Comment by Technetium1** [comment]
:open_mouth: My mistake! That is a local repo for me!

**Comment by xiota** [comment]
Planning to drop `ruffle-nightly-bin` because aside from version number, there's no effective difference from `-git` package.

Also, is there any point keeping `flashplugin`?  What browsers does it work with?

**Comment by xiota** [comment]
Dropping `flashplugin` because... no response to previous query and way past EOL.  Was full of security holes even when it was still actively maintained.

Dropping `exodus` because distribution prohibited by license.

> 1.3. Certain Restrictions.
>
> By accessing the Services, you agree not to: (a) license, sell, rent, lease,
transfer, assign, reproduce, distribute, host or otherwise commercially exploit
the Services or Exodus Content, or any portion thereof, including on a service
bureau or equivalent basis; ... (g) copy, reproduce, distribute,
republish, download, display, post or transmit any Exodus Content except as
expressly permitted herein; ...
