### ISSUE TITLE
[Request] Yandex Browser, not beta

### ISSUE THREAD

**Issue by cjvth** [chaotic-aur/packages#2031]
### Link to the package(s) in the AUR

[https://aur.archlinux.org/packages/yandex-browser](https://aur.archlinux.org/packages/yandex-browser)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Yandex Browser for Linux used to be called beta for years, but recently they decided to release it. But there is a problem with version numbering, current release version is 22.9.3 (year - month - number), but beta is 22.9.1, probably release contains some fixes that beta doesn't

**Comment by Technetium1** [comment]
[Section 4 of the license](https://yandex.com/legal/browser_agreement/) forbids redistribution, especially where there are any modifications done.

**Comment by OldKrab** [comment]
Why is it rejected, but yandex-disk is not? It has the same limitations: https://yandex.com/legal/desktop_software_agreement/

**Comment by OldKrab** [comment]
@Technetium1 There is "without the written consent from the Rights Holder" in license. Maybe try to get this consent? Yandex browser and yandex-disk are very popular software in some regions.

**Comment by Technetium1** [comment]
@OldKrab I appreciate that we _could_ ask for permission. I already distrust Yandex, and virtually any Russian company. Russia has been performing supply chain attacks everywhere it can since starting the war, and Yandex is most definitely a viable target, especially as a closed-source application.

I'm not interested in providing this, or any other packages from Yandex in the future. Even post-war. The exceptions would be the company being sold away from Russia, and the codebase being entirely open.
