### ISSUE TITLE
[Request] miktex

### ISSUE THREAD

**Issue by goingtosleep** [chaotic-aur/packages#2099]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/miktex

### Utility this package has for you

An on-demand package manager for latex.
For technical or academic folks, composing documents with latex is crucial. `texlive` package is quite bloated as it contains a bundle of latex packages. Also installing missing packages in the bundle is not straightforward.
As an alternative, `miktex` is very simple to use, just compile the latex document and it will automatically download only the missing packages.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Automatically bumped for rebuild because of library updates.  Does indeed need rebuild.
```
/opt/miktex/bin/miktex-console: error while loading shared libraries: libboost_locale.so.1.83.0: cannot open shared object file: No such file or directory
```

However, fails to build because of 404 error.  Someone else has already reported on aurweb.  `-git` package has same problem.  I am unable to locate the source of the problem.  If package cannot fixed, it will have to be dropped.

Package was last built May 2024.  I'm reasonably sure rebuilds have been needed since then, but there haven't been any reports or problems, so there may not be any active users.  Metrics 37.
