### ISSUE TITLE
[Request] Clash Verge

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#2106]
### Link to the package base(s) in the AUR

[AUR](https://aur.archlinux.org/packages/clash-verge)

### Utility this package has for you

A Clash GUI based on tauri.

[Clash](https://github.com/Dreamacro/clash) : A rule-based tunnel in Go.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
From what I can tell, clash is some sort of vpn.  Some related repos were archived and deleted.  Binaries became unavailable, and `clash-premium-bin` was deleted from AUR.  Probably other clash-related packages to follow.

I am removing them from the package lists, since they can no longer be rebuilt.  However, I am leaving the binary packages in the repo pending comment/discussion.  Is there value in continuing to make this available?
