### ISSUE TITLE
[Request] xcp

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2139]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/xcp

Note:  The developer has stated that this program is "never really intended ... to be a... replacement for cp, but as a sandbox for experimenting with UI and performance improvements."

### Utility this package has for you

xcp is an extended version of `cp` command. It provides a lot of features and has greater performance of `cp` during the copy process. Details: https://github.com/tarka/xcp

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because every version since 0.10.0 (Jun 2023), now at 0.16.0, has had test failures.  Not safe to bypass checks for packages that could result in data loss.  The developer has also stated that this program is "never really intended ... to be a... replacement for cp, but as a sandbox for experimenting with UI and performance improvements."

**Comment by xiota** [comment]
I reported the issue upstream and tests were updated.  So this can be added back if desired.

**Comment by D3vil0p3r** [comment]
> I reported the issue upstream and tests were updated. So this can be added back if desired.

I think yes, it could be good to take back.
