### ISSUE TITLE
[Outdated] `gzdoom`.

### ISSUE THREAD

**Issue by yum13241** [chaotic-aur/packages#2149]
### If available, link to the latest build

Doesn't exist.

### Package name

`gzdoom`

### Latest build

4.10.0

### Latest version available

4.9.0

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

https://github.com/zdoom/gzdoom is their GitHub.
*See* https://zdoom.org/wiki/Compile_GZDoom_on_Linux.
What happened to Zandronum and Raze?

It'd also be nice if you could build dev builds as `gzdoom-alpha`, and allow them to coexist.

**Comment by dr460nf1r3** [comment]
Thats nothing we would "fix" as the AUR package is currently flagged as outdated. Naturally we build the current AUR version, therefore the right way would be to report this to the AUR maintainer. 

> What happened to Zandronum and Raze?

What do you mean by that?

**Comment by Technetium1** [comment]
This belongs to #1615. It wasn't able to be added to a routine previously due to issues building a dependency. The reason it's 'disappeared' is due to a massive rebuild that happened; in the process, all packages that were not in a routine were removed.

- Was this [`raze`](https://aur.archlinux.org/packages/raze) supposed to be in that request as well? If so, can/should it be added to 1615's title?

**Comment by Technetium1** [comment]
Please open a new request for either `raze` or `raze-git` since they are not directly related to 1615
