### ISSUE TITLE
[Request] monkeysphere 

### ISSUE THREAD

**Issue by Smart123s** [chaotic-aur/packages#2276]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/monkeysphere

### Utility this package has for you

Leverage the OpenPGP web of trust for OpenSSH and Web authentication

Lol, I just used to to convert my GPG key to an OenSSH one.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Actually, build failed.

**Comment by Smart123s** [comment]
Building in chroot failed, I'm looking at it.

**Comment by Technetium1** [comment]
@Smart123s Please review this log and compare it to yours, if it's okay, we can skip the check. It fails since there's no IPC to connect to.

**Comment by Smart123s** [comment]
Yes, I also had to skip the checks.

The `openpgp2ssh` command and the monkeysphere manpage are both functional, so I suppose the other commands are fine too.

**Comment by xiota** [comment]
@dr460nf1r3 @Technetium1  Opinion?  Drop?

Build failure because of missing `libgcrypt-config`.  File was dropped from `libgcrypt` recently.  Other packages are affected (`rsyslog`).  No alternate or shim currently available on AUR.  While reasonable to wait for still-maintained projects, like `rsyslog` to be updated, projects that are unmaintained, like `monkeyspere` should probably be dropped.

**Comment by Technetium1** [comment]
@xiota I agree with that logic, and that it's reasonable to wait for `rsyslog`. Metrics: `2`

**Comment by dr460nf1r3** [comment]
Sounds reasonable indeed. Good find!
