### ISSUE TITLE
[Request] armcord-git

### ISSUE THREAD

**Issue by asdfzxcvbn** [chaotic-aur/packages#2281]
### Link to the package base(s) in the AUR

[armcord-git](https://aur.archlinux.org/packages/armcord-git)

### Utility this package has for you

a discord client that attempts to make discord more private, along with mod support.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
This would not be a very good package to add due to the lack of consistent releases which things I consider critical. Take a look at some of the things that have been fixed since the last release in Dec 2022: https://github.com/ArmCord/ArmCord/compare/dev...v3.1.4

Would you be opposed to [`armcord-git`](https://aur.archlinux.org/packages/armcord-git) instead @asdfzxcvbn?

**Comment by asdfzxcvbn** [comment]
no problem at all with that! the git version is fine.

**Comment by xiota** [comment]
Dropping because of persistent upstream issues that prevent the package from working normally.  Users are advised to build `aur/armcord-bin` on their own.
