### ISSUE TITLE
[Request] ns3 | Network Simulator | Required for college work

### ISSUE THREAD

**Issue by RohitSingh107** [chaotic-aur/packages#2340]
### Link to the package base(s) in the AUR

[ns3](https://aur.archlinux.org/packages/ns3)
https://aur.archlinux.org/packages/ns3

ns3 is a network simulator.

### Utility this package has for you

I need it for learning purposes.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
optdep `dia` is still a python2 monstrosity, so I'm adding `dia-git` so it can be satisfied

**Comment by Technetium1** [comment]
Build is currently failing: [ns3.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/ns3.log)

---

```md
# Issue 2340
dia-git # (dep ns3)
castxml # (dep ns3 python-pygccxml)
python-pygccxml # (dep ns3)
python-cxxfilt # (dep ns3)
python-pygraphviz # (dep ns3)
ns3
```
```
Add ns3, dia-git, python-pygccxml, python-cxxfilt, python-pygraphviz, python-pygccxml, castxml
```

**Comment by Technetium1** [comment]
"[NetAnim](https://www.nsnam.org/wiki/NetAnim) has not been actively maintained/improved since 2017." Unfortunately, it's required ([1](https://gitlab.com/nsnam/ns-3-dev/-/issues/821#optional), [2](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ns3#n18)) to compile correctly, and we're not going to provide Qt5, so this package will not be added. See #3157
