### ISSUE TITLE
[Outdated] Confirm Nvidia 390xx & 470xx rebuilds

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#2346]
### If available, link to the latest build

The following packages were in routine, but were not building, or even attempting to. They built fine when run manually. They should be watched for updates to confirm that the routine is building them as expected.

[nvidia-390xx-settings](https://aur.archlinux.org/pkgbase/nvidia-390xx-settings)
[nvidia-390xx-utils](https://aur.archlinux.org/pkgbase/nvidia-390xx-utils)
[nvidia-470xx-settings](https://aur.archlinux.org/pkgbase/nvidia-470xx-settings)
[nvidia-470xx-utils](https://aur.archlinux.org/pkgbase/nvidia-470xx-utils)

These just built:
`nvidia-390xx-utils`—`390.157-3`
`nvidia-470xx-utils`—`470.161.03-1`

Duplicates were just removed in https://github.com/chaotic-aur/packages/commit/cb008120a1c7197e3318a1c850a10b050b441729 so there is now only pkgbase, hopefully it helps avoid this in the future.

### Package name

`nvidia-{390xx,470xx}-{settings,utils}`

### Have you tested if the package builds in a clean chroot?

- [X] Yes

**Comment by dr460nf1r3** [comment]
Now this is a weird issue. If they still don't build we might try specifying the AUR url of the pkgbases manually 🤔 
I imagine this kind of makes sense though, since the name of the folder will be the pkgbase and not the one of the other packages built by the pkgbase. So the toolbox tries to build the wrong folder.
