### ISSUE TITLE
[Bug] ryujinx-git fails to compile

### ISSUE THREAD

**Issue by dnmodder** [chaotic-aur/packages#2385]
### What happens?

The ryujinx-git package should be using the AUR's dotnet-sdk-bin, but in the log I see that it continues to install dotnet-sdk from the official repositories and they are out of date, causing ryujinx-git not to compile.

### What is expected to happen?

You should install the dotnet-sdk-bin and dotnet-runtime-bin packages

### If possible, please attach logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/ryujinx-git.log

**Comment by dr460nf1r3** [comment]
Now this is interesting. We will need further investigation!

**Comment by dr460nf1r3** [comment]
So we had an outdated interference in place, though it wasn't the reason for the whole dependency hell. Dotnet versions seem hella fucked up. Trying to force installing the actual `-bin` packages via interfere is also impossible, as it seems. From what I read in the latest commit, one has to not only install the (make)deps, but the entire Dotnet stack with mixed versions in order to compile this.

**Comment by dnmodder** [comment]
@dr460nf1r3 Should I modify the pkgbuild and include the dotnet binaries directly or something? It's the only thing I can think of right now or wait for them to update in the Arch repositories, but Ryujinx very often updates to a newer version.

**Comment by dr460nf1r3** [comment]
If you get it to work, fine!

**Comment by dnmodder** [comment]
I think I fixed it, wait for it to compile https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ryujinx-git
