### ISSUE TITLE
[Request] Flight Core

### ISSUE THREAD

**Issue by Pakrohk** [chaotic-aur/packages#2520]
### Requested Package:

[flightcore](https://aur.archlinux.org/packages/flightcore)

### Purpose and Use?

A Northstar installer, updater, and mod-manager For titanfall 2 modding and custom server framework.

### Benefits?

Fast and easy to use Northstar installer, updater, launcher, and mod-manager. Features built-in mod browser and allows for easy installation of pre-release versions of Northstar.

Supports Windows and Linux. 

### Copyright License?

MIT : https://github.com/R2NorthstarTools/FlightCore/blob/main/LICENSE

### Expected interest

Only me.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

### More information

This pack is only for my needs right now, but it might be useful for any gamer playing Titanfall 2, especially since it has better anti-cheat.

**Comment by Technetium1** [comment]
Build fails, please report on AUR: [flightcore.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/flightcore.log)

**Comment by xiota** [comment]
`rust` packages are a pain... they download and rebuild all rust dependencies.  Is there a way to cache them?

**Comment by begin-theadventure** [comment]
> Is there a way to cache them

sccache and the `--keepsrc` flag for paru.

There's also a [-bin package](https://aur.archlinux.org/packages/flightcore-bin), try it.

**Comment by Technetium1** [comment]
@xiota There is not :(

**Comment by begin-theadventure** [comment]
Not in in clean chroot, I guess?
But in general they can be with sccache and paru --keepsrc.

**Comment by Technetium1** [comment]
@begin-theadventure Appreciate the suggestion, but I don't think that either are feasible here: https://github.com/chaotic-aur/toolbox

**Comment by Technetium1** [comment]
I guess GitHub no longer lets me close issues with keywords…?

This was just added in: https://github.com/chaotic-aur/packages/commit/f58f1f4486d14d81e18efc4c19858f3ba6cc1ddc

**Comment by xiota** [comment]
Fails to build.  AUR maintainer notified.  Will drop if not fixed because package has low usage.  Metrics 3.

**Comment by xiota** [comment]
@begin-theadventure Re recent AUR comment that you're having difficulty with this package.  Last year, I noted the changes needed.  I will write out the steps here.  If not fixed tomorrow, I will be dropping the package.  (If you need more time or help, comment to say so.)  (I will delete my AUR comments because I will not be following the package any longer.)

* Update `pkgver` to `3.2.0`.  Set `pkgrel` to `1`
* Update `sha256sums` by running `updpkgsums`.
* Update depends to `webkit2gtk-4.1`.  (In case not clear, remove `webkit2gtk`.)
* Change the binary name in `package()` to `flightcore` (from `flight-core`).
* (Optional) Remove the docs.  They're pointless.  People who want to read them can do so on the repo or from the source tarball.
* Clear your build cache.
* Rebuild in clean chroot.

Re the pinned comment.  Your phrasing doesn't really characterize the developer's response to your query.  He did not say he would not fix any problems associated with the AUR package.  He said he would not fix AUR-specific problems (that is, problems that affect only AUR).  For instance, I suspect he might not want to deal with problems in a package that is out of date nearly a year that are already fixed in more recent releases.

![Image](https://github.com/user-attachments/assets/3346cd22-81e3-4bcc-b109-a64ad84206d4)

**Comment by xiota** [comment]
Dropping because of poor maintenance.  Declared deadline passed without action or comment from any potentially interested parties.  Usage too low to be worth fixing with interfere.  Metrics 5.
