### ISSUE TITLE
[Request] nerd-fonts-noto-sans-mono-extended

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2567]
### Requested Package:

[nerd-fonts-noto-sans-mono-extended](https://aur.archlinux.org/packages/nerd-fonts-noto-sans-mono-extended)

### Purpose and Use?

Noto Sans Mono including Condensed variants. Sourced directly from Google, patched with the Nerd Fonts Patcher.

### Benefits?

Google fonts but patched with the Nerd Fonts Patcher (https://github.com/ryanoasis/nerd-fonts)

### Copyright License?

None

### Expected interest

Many.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by Technetium1** [comment]
Was flagged out of date due to a new release.

**Comment by xiota** [comment]
Could someone explain the whole "nerd fonts" thing to me?

**Comment by Technetium1** [comment]
@xiota the gist is that they are enhanced versions of existing fonts programmers prefer with proper glyph support and some extras (namely icons). More info here: https://github.com/ryanoasis/nerd-fonts/ & here: https://github.com/ryanoasis/nerd-fonts/wiki#what

**Comment by D3vil0p3r** [comment]
@Technetium1 AUR package has been fixed.

**Comment by xiota** [comment]
@D3vil0p3r  Package is out of date.  Repo no longer exists / moved.  Patcher updated to 3.2.1.  Also, benefit of this package over `extra/ttf-noto-nerd`?

**Comment by D3vil0p3r** [comment]
If I remember well, this package has more glyphs. Currently I manage the AUR package but I cannot update it because svn does not allow me to get a subdir from source. If I use git, it takes too much time. I left a comment about it on AUR page. Any ideas?

**Comment by xiota** [comment]
All packages are going to be rebuilt soon, and broken packages will be dropped.  Metric 41.

If I were maintaining the package, I would retire it (open deletion request) because it's too complicated to fix and doesn't have clear benefit.

I don't know any way to grab directories from git, so would have to download everything or individual files.  There are 36 Noto mono files and probably 15-20 glyph files.

From the nerd fonts readme, the prepatched fonts probably already have all the glyphs because the proposed benefit of self-patching is to exclude symbols.

> Option 2: Patch your own font
>
> Patch your own variations with the various options provided by the font patcher (i.e. not include all symbols for smaller font size)

**Comment by D3vil0p3r** [comment]
> From the nerd fonts readme, the prepatched fonts probably already have all the glyphs because the proposed benefit of self-patching is to exclude symbols.

Do you mean the `extra/ttf-noto-nerd` should contain all the glyphs?

**Comment by xiota** [comment]
> Do you mean the `extra/ttf-noto-nerd` should contain all the glyphs?

That would be my interpretation.

Someone replied to your query:

> Maybe the new locations are setup differently ?

However, I already tested.  It seems that whatever functionality you were using may have been shutdown by github.

**Comment by D3vil0p3r** [comment]
@xiota The suggested NotoSansMono new source is good. What I just need to fix and update it is to understand how to retrieve the glyphs (third source of the PKGBUILD) to avoid to pull the entire git repository. I opened this issue on the upstream project: https://github.com/ryanoasis/nerd-fonts/issues/1656 but if this will be managed, I think we can still maintain this package (also in AUR).

**Comment by D3vil0p3r** [comment]
@xiota I fixed the AUR package. It has been updated.

**Comment by Technetium1** [comment]
Build completed: [nerd-fonts-noto-sans-mono-extended.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/nerd-fonts-noto-sans-mono-extended.log)

**Comment by xiota** [comment]
Looks like "extended" is a misnomer because `extra/ttf-noto-nerd` has all variants and same number of glyphs.  The AUR package uses slightly different family names and ttfautohint.

The following changes are recommended:
* Resubmit package to AUR with corrected name.
* Change description to: "Noto Sans Mono, patched with Nerd Fonts Patcher"
* Change URL to: https://github.com/ryanoasis/nerd-fonts
* Change license to "OFL-1.1"
* Remove provides.  Not drop-in replacement because family names slightly different.
* Remove conflicts.  Not needed because font location and family names are different.

**Comment by D3vil0p3r** [comment]
Which name do you suggest?

**Comment by xiota** [comment]
> Which name do you suggest?

`nerd-fonts-noto-sans-mono` or `ttf-noto-sans-mono-nerd`

Also, do *not* use replaces.  If you want to help users migrate from old package, turn it into a metapackage.

**Comment by D3vil0p3r** [comment]
> Looks like "extended" is a misnomer because `extra/ttf-noto-nerd` has all variants and same number of glyphs. The AUR package uses slightly different family names and ttfautohint (probably different patcher config).

https://aur.archlinux.org/packages/nerd-fonts-noto-sans-mono

On the old one I submitted a "Merge" request.

**Comment by xiota** [comment]
I would have opted for a deletion request.  There's no point keeping the old comments, and the vote count is low.
