### ISSUE TITLE
[Request] NVIDIA 525xx Packages

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#2601]
### Package:

https://aur.archlinux.org/packages/opencl-nvidia-525xx
https://aur.archlinux.org/packages/nvidia-525xx-utils
https://aur.archlinux.org/packages/nvidia-525xx-dkms
https://aur.archlinux.org/packages/nvidia-525xx
https://aur.archlinux.org/packages/lib32-opencl-nvidia-525xx
https://aur.archlinux.org/packages/lib32-nvidia-525xx-utils
https://aur.archlinux.org/packages/nvidia-525xx-settings

### Purpose:

These are production branch drivers for nvidia devices, rather than the bleeding edge ones.

### Benefits:

OpenCL implemention for NVIDIA, 525 branch
NVIDIA drivers utilities, 525 branch
NVIDIA drivers - module sources, 525 branch
NVIDIA drivers for linux, 525 branch
OpenCL implemention for NVIDIA (32-bit), 525 branch)
NVIDIA drivers utilities (32-bit), 525 branch
Tool for configuring the NVIDIA graphics driver, 525 branch

### Building:

I did build this package, but TKG version

### Copyright:

custom license [nVidia]

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Nothing.

**Comment by xiota** [comment]
Dropped because state of drivers is different than when requested.  This package is not among those recommended at [ArchWiki: NViDIA](https://wiki.archlinux.org/title/NVIDIA).

<details><summary>Metrics...</summary>

* lib32-nvidia-390xx-utils # 72
* lib32-nvidia-470xx-utils # 140
* lib32-nvidia-525xx-utils # 18
* lib32-opencl-nvidia-390xx # 38
* lib32-opencl-nvidia-470xx # 73
* lib32-opencl-nvidia-525xx # 7
* nvidia-340xx # 22
* nvidia-340xx-dkms # 64
* nvidia-340xx-lts # 14
* nvidia-340xx-lts-dkms # 15
* nvidia-340xx-settings # 31
* nvidia-340xx-utils # 89
* nvidia-390xx-dkms # 230
* nvidia-390xx-settings # 92
* nvidia-390xx-utils # 443
* nvidia-470xx-dkms # 386
* nvidia-470xx-settings # 132
* nvidia-470xx-utils # 398
* nvidia-525xx-dkms # 59
* nvidia-525xx-settings # 16
* nvidia-525xx-utils # 83
* opencl-nvidia-340xx # 20
* opencl-nvidia-390xx # 99
* opencl-nvidia-470xx # 157
* opencl-nvidia-525xx # 34
</details>
