### ISSUE TITLE
[Request] applet-window-buttons-git

### ISSUE THREAD

**Issue by mauriciodelima21** [chaotic-aur/packages#2603]
### Package:

[applet-window-buttons-git](https://aur.archlinux.org/applet-window-buttons-git.git)

### Purpose:

Utiliso nas minhas instalação e numa custom com archiso

### Copyright:

GPL

### Expected Interest:

Most

### Already available?

Yes

### Unique request?

No

### Banned package?

Yes

**Comment by dr460nf1r3** [comment]
We already had this in the past, but there are 2 reasons for not having it: it's no longer developed actively, so there is no real benefit against using the stable version and the AUR package no longer exists.

**Comment by xiota** [comment]
@mauriciodelima21  Please edit your request to update it:

* Fix the link.  You are pointing to the git repository.  The link needed is to the AUR package webpage.

* Update the purpose to explain what this package does.  Update benefits to explain why *other* people might want to use it.  "I use this package" isn't helpful.

**Comment by mauriciodelima21** [comment]
I have a distribution called "uaiso" and I'm using this package to customize the KDE layout.

https://so.uai21.online/

**Comment by xiota** [comment]
@mauriciodelima21  I recall trying both the normal and git packages some months ago, and they did not work properly.  I am willing to re-evaluate, provided the initial request is updated.  Also, dr460nf1r3 has already rejected this package.  You need to update the request to convince him to reconsider.

* Fix the link.  This is vital as the correct link helps maintainers to properly evaluate the package.  The current link returns a 404 error, which makes it look like the package does not exist.
* Explain what the package does.  "customize the KDE layout" is not detailed enough.  Specifically, what customization does it provide?  Is it functional or mere eye-candy?  If functional, what is the use case?
* Explain why *other* people would want this package.  "I'm using this" is *not* helpful.  What use cases does this package help with?
* Explain why you need the -git version.  Otherwise, specify whether the normal version would be sufficient.

**Comment by xiota** [comment]
Now I understand dr460nf1r3's comment... stable version = latest commit and stable version is already available as `extra/plasma5-applets-window-buttons`, so building `-git` version is pointless.
