### ISSUE TITLE
[Request] wine-wow64

### ISSUE THREAD

**Issue by haxyom** [chaotic-aur/packages#2635]
### Package:

[wine-wow64](https://aur.archlinux.org/packages/wine-wow64)

### Purpose:

Wine compatibility layer, built in wow64 experimental mode.
Can run 32 bit programs without any 32 bit dependencies.

### Benefits:

Avoid to install 32 bit dependencies.

### Copyright:

LGPL

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Package has been built and available in chaotic for testing.  Has not been added to the package lists.

**Comment by Brueggus** [comment]
> @haxyom @Brueggus Please test and let me know if it works as expected.

Works flawlessly for me. Thanks for your effort!

**Comment by haxyom** [comment]
Fine for me too. Thank you!

**Comment by xiota** [comment]
`aur/wine-wow64` is tracking release candidates.  To provide a  more stable experience, this package is being switched to `aur/wine-wow64-git` + interfere.

**Comment by xiota** [comment]
`multilib/wine` 10.8-2 will have wow64 mode enabled.  After the multilib package is out of testing, `wine-wow64` will be converted to a meta package to migrate users.  A new package may be created later to remove the left-over meta packages.

`wine-wow64-git` will be replaced with a custom `wine-git` package.  The -git package will eventually be dropped because new versions of wine are released so frequently.

**Comment by xiota** [comment]
Converting to metapackage soon because `extra/wine` and `extra/wine-staging` 10.9-1 have new wow64 mode enabled.

Metrics:

* wine-wow64 # 510
* wine-staging-wow64 # 540
