### ISSUE TITLE
[Bug] Read before requesting rebuilds or reporting out-of-date

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#2669]
Before requesting rebuilds or reporting out-of-date, **please check the build log to ensure the cause is not related to this issue**.  If so, instead of opening a new issue, comment here with the package name and link to the log file.  Thank you.

### Packages:

many

### What happens?

After server update, attempts to rebuild packages fail with error similar to:
```
Failed to create /../../machine-pkg6caf2d22b4e.scope/payload subcgroup: Not a directory
```

### What is expected to happen?

Packages should start building without this error.

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/

### More information

Issue is being worked on.

**Comment by dr460nf1r3** [comment]
This seems to occur only on sessions, that are not being initiated via `nixos-container root-login`. This seems to be cgroup restriction related, though, further investigation is needed. 

Regular routines should *not* be affected.

**Comment by dr460nf1r3** [comment]
The root cause seems to be improperly mounted `/sys/fs/cgroup` of the builders container, preventing any startups of the nspawn containers used to build in clean environments. Remounting those fixes the issue seen in the logfiles. 

Actually this should be done here already:

https://github.com/garuda-linux/infrastructure-nix/blob/main/nix/garuda/common/nspawn-containers.nix#L158

A permanent solution still needs to be found, for now builds will be running until a container restart however.

**Comment by dr460nf1r3** [comment]
Meanwhile, a permanent solution has been found.
