### ISSUE TITLE
Request: Whitesur Themes

### ISSUE THREAD

**Issue by dr460nf1r3** [chaotic-aur/packages#269]
The theme consists of these packages: 
- whitesur-cursor-theme-git
- whitesur-gtk-theme-git
- whitesur-kde-theme-git

Also, 
- ttf-meslo-nerd-font-powerlevel10k
- firefox-extension-canvasblocker

**Comment by dr460nf1r3** [comment]
All working as expected, thanks!

**Comment by xiota** [comment]
@dr460nf1r3 Do you still want to keep [`aur/plasma5-themes-whitesur-git`](https://aur.archlinux.org/packages/plasma5-themes-whitesur-git)?

Fails to build because upstream change.  AUR package orphaned, so you could adopt.  Also looks like upstream may have been updated to add plasma6 support, so could turn into a split package. Metrics 7.

**Comment by dr460nf1r3** [comment]
Can be dropped imo. It was used as Garuda theme in the very early days, but no more nowadays as far as I'm aware.
