### ISSUE TITLE
[Request] colloid-gtk-theme-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#2691]
### Package:

https://aur.archlinux.org/packages/colloid-gtk-theme-git

### Purpose:

Really beautiful and well maintained theme that comes with a ton of styles.

### Copyright:

GPL3

### Expected Interest:

Everyone

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by tio-trom** [comment]
The conflicts and provides for the chaotic aur package for all of the theme's variations are not updated and they conflict with each other:

As an example AUR package - https://aur.archlinux.org/packages/colloid-dracula-gtk-theme-git

And Chaotic AUR package - https://archlinux.pkgs.org/rolling/chaotic-aur-x86_64/colloid-dracula-gtk-theme-git-2024.04.14.r0.g2949b6a7-1-any.pkg.tar.zst.html

All of the packages are:

```
colloid-gtk-theme-git
colloid-dracula-gtk-theme-git
colloid-everforest-gtk-theme-git
colloid-gruvbox-gtk-theme-git
colloid-nord-gtk-theme-git
```

This was fixed yesterday and I am not sure if you need to push this manually or it is automated.

Thanks!

**Comment by Technetium1** [comment]
@tio-trom already done automatically!

**Comment by Technetium1** [comment]
Oh, I see exactly now, it didn't update and it should have!

**Comment by xiota** [comment]
It's a git package.  If it was already built before the maintainer changed the PKGBUILD, it won't rebuild.  It needs to be bumped or wait for the next git commit.

**Comment by futureisfoss** [comment]
The package maintainer on AUR did bump the version when they changed the `provides` & `conflicts` value, see this commit - https://aur.archlinux.org/cgit/aur.git/commit/?h=colloid-gtk-theme-git&id=75aaf119fd4234cb2d4d1b95cff1ec8d2155e8b5

Chaotic-aur did not reflect this change even tho it updated the version, I'm not sure why.....

**Comment by xiota** [comment]
@futureisfoss -git packages auto update pkgver whenever they're built.  You can try this yourself.  Edit the PKGBUILD so that pkgver=0.0.0.  Then run `makepkg`.  It will update pkgver.  When it finishes making the pacakge, make whatever changes you want to the PKGBUILD.  Run `makepkg` again.  It will quit error:
```
==> Starting pkgver()...
==> ERROR: A package has already been built. (use -f to overwrite)
```

**Comment by tio-trom** [comment]
All is good now. Thank you people!

**Comment by futureisfoss** [comment]
@tio-trom: I think I get what @xiota was trying to explain, `-git` packages usually set their `pkgver` dynamically using the latest git commit of a repo - this means that chaotic-aur could've built the package before the AUR maintainer actually fixed the conflicts and they'd still show the same versions.

**Comment by xiota** [comment]
colloid related packages are being considered for drop because colloid-icon-theme-git has repeatedly caused problems with the build server.  Also considering options to mitigate with interfere.  Will decide maybe this weekend.

Metrics (likely inflated by 10-30x because -git packages):

* colloid-catppuccin-gtk-theme-git # 420
* colloid-catppuccin-theme-git # 111
* colloid-cursors-git # 201
* colloid-dracula-gtk-theme-git # 385
* colloid-dracula-theme-git # 51
* colloid-everforest-gtk-theme-git # 376
* colloid-everforest-theme-git # 25
* colloid-gruvbox-gtk-theme-git # 396
* colloid-gruvbox-theme-git # 51
* colloid-gtk-theme-git # 472
* colloid-icon-theme-git # 312
* colloid-nord-gtk-theme-git # 383
* colloid-nord-icon-theme-git # 62

**Comment by tio-trom** [comment]
What re the problems that they are causing? And is it just the icon theme that is causing the issues? If so is it possible to only drop that? This Colloid theme is really good and well maintained.

**Comment by xiota** [comment]
colloid-gtk-theme-git and colloid-icon-theme-git both freeze at the end, blocking the rest of the queue.  Don't know why.  Added interferes to limit rebuilds to make them less disruptive.

**Comment by tio-trom** [comment]
Building them locally is fine. But yes see if you can make it work...thanks for trying!
