### ISSUE TITLE
[Request] pulseaudio-module-xrdp

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2701]
### Package:

[pulseaudio-module-xrdp](https://aur.archlinux.org/packages/pulseaudio-module-xrdp)

### Purpose:

Integration of pulseaudio on XRDP for RDP session.

### Benefits:

It has a very big benefit for all those RDP sessions (i.e., exposed by a docker container or WSL or a virtual machine) that provides the sound support that normally is not present.

### Copyright:

LGPL

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by D3vil0p3r** [comment]
In 1 week I should back home. Then I will give a look to it. Ty for reporting @xiota

**Comment by xiota** [comment]
@D3vil0p3r aurweb doesn't show you as the maintainer.

**Comment by D3vil0p3r** [comment]
@xiota I tested in clean chroot and it builds correctly. Which error are you getting during building? If you get `xrdp` missing, it is because you need to add Chaotic AUR repository in chroot environment (or installing xrdp package manually).

**Comment by xiota** [comment]
Problem was expired SSL cert for about a month.  Looks like they've fixed it.

**Comment by xiota** [comment]
Another problem is [`PKGBUILD`:14](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pulseaudio-module-xrdp#n14):
```
_pulseaudio_ver="$(pulseaudio --version | awk '{print $NF}')"
```
causes the error:
```
/home/builder/build/PKGBUILD: line 14: pulseaudio: command not found
```

`pulseaudio` is installed by `makepkg` later in the process.

**Comment by D3vil0p3r** [comment]
I noted it but the PKGBUILD should have a line saying that if you dont get the version, consider the v. 17

**Comment by xiota** [comment]
Dropping `pulseaudio-module-xrdp` because fails to build and Pipewire is now preferred on Arch.  Metrics:

* pulseaudio-module-xrdp # 19
* pipewire-module-xrdp # 40

**Comment by D3vil0p3r** [comment]
Hey, I tried to build it on a modified AUR version and it works. This Xrdp module is useful for Win Kex in WSL environment. If I push AUR maintainer to fix its issue, could you reupload again it in Chaotic?

**Comment by xiota** [comment]
I'll re-add as a custom `-git` version with plan to drop when usage is "too low".  This way the package should keep itself updated with minimal intervention until it's no longer needed.

For the sake of a working AUR, you can notify the current maintainer of the problem with lines 14-15.  It's caused by `makepkg` running through the PKGBUILD several times.  On the first pass, the variable is set to `17.0`.  On a subsequent pass, it's set to `17.0-43-g3e2bb`.  The checksum is left blank because the file doesn't exist.
```
_pulseaudio_ver="$(pulseaudio --version | awk '{print $NF}')"
: "${_pulseaudio_ver:=17.0}"

sha256sums=(
    'SKIP'
    "$(curl -fs "${source[1]}.sha256sum" | awk '{print $1}')"
)
```

I'd recommend parsing `pacman` output because trying to use `pulseaudio` could have similar problems in the future.
```
_pulseaudio_ver="$(LANG=C LC_ALL=C pacman -Si pulseaudio | grep -Pom1 '^Version\s+:\s+\K[0-9]+\.[0-9]+')"
```
