### ISSUE TITLE
[Request] motivewave

### ISSUE THREAD

**Issue by xavierbaez** [chaotic-aur/packages#2750]
### Package:

[motivewave](https://aur.archlinux.org/packages/motivewave)

### Purpose:

Advanced trading and charting application.

### Copyright:

https://www.motivewave.com/support/terms_of_service.htm

### Expected Interest:

Few

### Already available?

Yes

### Unique request?

No

### Banned package?

No

**Comment by xiota** [comment]
There is no conflict because `motivewave` is no longer in chaotic.  It was replaced `motivewave-latest-bin` because `motivewave` was broken for four months, 11 releases out of date.  An interfere was created to update it, but that was also broken.  `motivewave-latest-bin` will autoupdate with each release with minimal maintainer intervention.

It is normal for packages to provide/conflicts with other packages.  The package manager prevents them from being installed simultaneously.  Since both packages provide the exact same program, there is no need to install both at the same time.  So any potential conflict is irrelevant.

As stated in https://github.com/chaotic-aur/packages/commit/cdbf634c892d37d2d41ea1f03bdb696fc98f824e#commitcomment-125439809, I will revert the change if @alexjp wishes.

**Comment by xiota** [comment]
> Xiota never mentioned the new package he created conflicts with another package. Duplicated package.

See #2748.

> Already available?
>
> Yes; creating this issue to migrate `motivewave` → `motivewave-latest-bin`.

**Comment by alexjp** [comment]
I don't see what is the big deal with these issues.

Since Motivewave is a paying app, its both usefull to have a specific version and a latest version.

I had been updating motivewave manually here, so having an "auto up to date" is cool.
Since they conflict between each other, there is no issue that they use the same files.

@xavierbaez : 
- I would not see a problem in having both packages, since motivewave doesn't update that often and are binaries.

- Why so spicy in the aur comments? @xiota does a lot of good work here (and probably other places I dont know) and its not like motivewave has a lot of users running arch. its probably ??dozen of us?? ? I dont see the big deal!

**Comment by xavierbaez** [comment]
@alexjp not the spicy is coots who did a package that conflicts with motivewave and he removed motivewave from chaotic AUR himself

I have never talked to him

MotiveWave has planned an iOS app so they don't send release notes or emails anymore. And Xiota would still need to change the files for the people that don't use Chaotic AUR

The fact that he created the package  himself and he created the error himself and he wrote the code himself to remove MotiveWave from the Chaotic AUR doesn't shows you a conflict of interests where he never talked to me and in one day he does everything by himself?

**Comment by alexjp** [comment]
> The fact that he created the package himself and he created the error himself and he wrote the code himself to remove MotiveWave from the Chaotic AUR doesn't shows you a conflict of interests where he never talked to me and in one day he does everything by himself?

@xavierbaez I think you are attributing bad faith where there is no reason. The reason he did all that "in a day", its because he has been working,cleaning,fixing,developing packages here on chaotic aur for some time now.
You can see his "history" of all the work he has done.

@xavierbaez could this be solved through adding back motivewave package and keeping both?
@xiota any issue with this also?

**Comment by xiota** [comment]
I don't see why both packages are needed, but if everyone else agrees that having both in the repository is worthwhile, I will add `motivewave` back.

**Comment by xavierbaez** [comment]
Okay so please add MotiveWave back since you're the one that deleted it.

**Comment by xavierbaez** [comment]
> could this be solved through adding back motivewave package and keeping both

Yea this could be resolved by keeping both.

**Comment by xiota** [comment]
@xavierbaez I have been more than patient with you.  Take a look at the comments you have posted.  Ask yourself, how likely would you be to want to work with someone who left comments like that to you?

You've accused me of wanting to have the package in my name.  My interest is in keeping packages on chaotic-aur working.  When you don't maintain your packages, someone here has to fix or drop them.  Don't want anyone to interfere?  Keep your package up to date.

`motivewave` was flagged out of date from 2023-08-01 until 2023-08-24, when the orphan request was opened.  This is over three weeks.  According to AUR submission guidelines, two weeks is a sufficient amount of time to wait before opening an orphan request.  Don't want orphan requests?  Keep your package up to date.

The orphan flag on `motivewave` was removed shortly after the package was updated.

I have already explained elsewhere the rationale for creating the new package.  Even though it installs the same program, the packaging itself is functionally different because it is *autoupdating*.  Like -git packages, it does not require any changes except for packaging issues.  Like -git packages, it is best described with a new suffix.  There are many packages on AUR that install the same program.  They can coexist without any issue.  So I am asking you to cancel your deletion requests.

Then if you want help with `motivewave`, you can post a comment indicating what contribution you are seeking.  Or if you just don't want any interference with your maintenance activities, just keep it up to date.

**Comment by xavierbaez** [comment]
> I don't see why both packages are needed, but if everyone else agrees that having both in the repository is worthwhile, I will add `motivewave` back.

So why you didn't add it back?
Everyone in AUR helps, you didn't.
You just control Chaotic AUR.
You opened the issue.
You accepted the issue.
Now you are closing this issue.

Personally, why does it bother you to add motivewave back???

**Comment by xavierbaez** [comment]
@alexjp so why he wants both packages in AUR yet he insists it's a good idea to have only one package in Chaotic AUR???

**Comment by xiota** [comment]
@xavierbaez

**click → 6b1ad129b278fe38e6e2f4aa495306840c558cb9**

**Comment by alexjp** [comment]
> @alexjp so why he wants both packages in AUR yet he insists it's a good idea to have only one package in Chaotic AUR???

@xavierbaez because, and assuming the motivewave package will be updated and mantained, are kinda similar. (only difference is that the motive-latest-bin is always latest, and yours can be fixed to a specific version, which can be helpful to ppl that bought it but have no subscription for updates active).

@xavierbaez please stop with the attacks on @xiota. He has been doing an awesome work trying to lessen the "chaotic" out of "chaotic-aur", but ultimately the owners of the builders/machines are who decide things.

Since the package is back, and hopefully everyone happy, I hope we can get past this and treat each other with more trust and respect.

**Comment by xavierbaez** [comment]
@alexjp the package motivewave is ***NOT*** back on Chaotic AUR.
It's never about an attack if anything the takeover was done by him without helping the AUR community. He took over in 12 hours he did everything. If he adds the motivewave package back, then this issue is addressed. Him saying it's a personal thing about his patience etc, is exactly the opposite of addressing this issue. He wrote the code to replace a packet with HIS package. And it is not like Git because his spec is the same as mine. All these two packages do is pull from motovewave.com

So based on "feelings" he can close am issue?

You said there is no issue by having both packages. It's Xiota the one who closed the issue and no, the package never made it back to Chaotic AUR

**Comment by xiota** [comment]
@xavierbaez I've already asked you to stop harassing me.  Your behavior is inappropriate and in violation of both Arch and Chaotic AUR Codes of Conduct.  While I understand that you are trying to inconvenience me by spamming the comments at both aurweb and chaotic-aur, doing so also inconveniences users of the packages who have opted in to notifications and chaotic-aur maintainers who receive notifications on all issues here.

I advise you to exercise some self control and patience.  If you don't understand something, you should ask, rather than lash out and escalate your disruptive behaviors.  This issue was closed when `motivewave` was added back to the package list.  See 6b1ad129b278fe38e6e2f4aa495306840c558cb9.  The servers update and rebuild on a schedule.  Some packages, including `motivewave`, are scheduled to rebuild nightly, so it can take a couple days before the package is available for download.

**Comment by dr460nf1r3** [comment]
> Why so spicy in the aur comments? @xiota does a lot of good work here (and probably other places I dont know) and its not like motivewave has a lot of users running arch. its probably ??dozen of us?? ? I dont see the big deal!

Word, I support this as well and am not seeing the big deal either. It is common AUR for users to create multiple packages for different purposes - you see that at least 2 people are finding this package useful already.

> not spicy the person who created a package that conflicts with motivewave and he removed motivewave from chaotic AUR himself

Definitely spicy as in rejecting objectively given arguments and not accepting any other solution but `motivewave` being the sole package to provide the application on AUR. Spicy also as in adding passive-aggressive comments and lots of "???". 

> My interest is in keeping packages on chaotic-aur working. When you don't maintain your packages, someone here has to fix or drop them. Don't want anyone to interfere? Keep your package up to date.

> `motivewave` was flagged out of date from 2023-08-01 until 2023-08-24, when the orphan request was opened. This is over three weeks. According to AUR submission guidelines, two weeks is a sufficient amount of time to wait before opening an orphan request. Don't want orphan requests? Keep your package up to date.

These are more than sufficient reasons for all of this. 

> yet he insists it's a good idea to have only one package in Chaotic AUR???

From our perspective (as providers of Chaotic-AUR, a custom Arch repository) its of no use to have both of them if they provide the exact same content since its basically a waste of mirror's space. 

> He has been doing an awesome work trying to lessen the "chaotic" out of "chaotic-aur", but ultimately the owners of the builders/machines are who decide things.

Xiota has proven to make good decisions in the past as well and I have to agree with this one as well. 

> @alexjp the package motivewave is _**NOT**_ back on Chaotic AUR. It's never about an attack if anything the takeover was done by him without helping the AUR community. He took over in 12 hours he did everything. If he adds the motivewave package back, then this issue is addressed. Him saying it's a personal thing about his patience etc, is exactly the opposite of addressing this issue. He wrote the code to replace a packet with HIS package. And it is not like Git because his spec is the same as mine. All these two packages do is pull from motivewave.com
> 
> So based on "feelings" he can close an issue?
> 
> You said there is no issue by having both packages. It's Xiota the one who closed the issue and no, the package never made it back to Chaotic AUR

Please get your facts straight, there is **no** takeover, the package **was** added back and yes, xiota **has** been patient with you. The amount of time I had to invest into reading through this entire bullshit drama made up because of hurt feelings can be counted into this as well :) 

In the end you have your package back in the repository. Make sure to keep it updated and stop those childish attacks on other people trying to do good. It makes you look bad in everyone else's eyes.

**Comment by xiota** [comment]
@xavierbaez `motivewave` was picked up by the build server and now available in the repository.  However, I noticed an issue with the packaging.  The `PKGBUILD` and `.SRCINFO` do not match.  Not remedying this issue could be grounds for removal from chaotic-aur because it a way that malicious content could be hidden.

`.SRCINFO` should *not* be manually edited.  Instead, autogenerate it by running the following command prior to pushing updates:
```
makepkg --printsrcinfo >| .SRCINFO
```

If you have not already, please review the following ArchWiki pages:

* [Arch package guidelines](https://wiki.archlinux.org/title/Arch_package_guidelines)
* [AUR submission guidelines](https://wiki.archlinux.org/title/AUR_submission_guidelines).  The section [Publishing new package content](https://wiki.archlinux.org/title/AUR_submission_guidelines#Publishing_new_package_content) describes updating `.SRCINFO`.

**Comment by xavierbaez** [comment]
The only thing that did was change pkgrel to 1

**Comment by xiota** [comment]
@xavierbaez  In these two commits, you manually edit `.SRCINFO`: [2941953](https://aur.archlinux.org/cgit/aur.git/commit/?h=motivewave&id=2941953be7ac30148d4b4ad1203f79f5166dc189), [e662296](https://aur.archlinux.org/cgit/aur.git/commit/?h=motivewave&id=fe6622969cc4f3951a61b84660a556cbb0bb2ab5).  It is apparent because `.SRCINFO` is the only file that was modified.  This can be confirmed by examining the [`PKGBUILD`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=motivewave&id=fe6622969cc4f3951a61b84660a556cbb0bb2ab5) from the second commit.

The differences from the auto-generated `.SRCINFO` can easily be reviewed:
```
$ git clone https://aur.archlinux.org/motivewave.git
$ cd motivewave
$ git diff
$ makepkg --printsrcinfo >| .SRCINFO
$ git diff
diff --git a/.SRCINFO b/.SRCINFO
index cdc5266..64e2d20 100644
--- a/.SRCINFO
+++ b/.SRCINFO
@@ -1,7 +1,7 @@
 pkgbase = motivewave
        pkgdesc = Advanced trading and charting application.
        pkgver = 6.7.10
-       pkgrel = 2
+       pkgrel = 1
        url = https://www.motivewave.com
        arch = x86_64
        license = custom
@@ -11,9 +11,7 @@ pkgbase = motivewave
        depends = gtk3
        depends = java-runtime
        depends = xorg-xrandr
-       provides = motivewave
-       conflicts = motivewave-latest-bin
-       source = motivewave-6.7.10.deb::https://downloads.motivewave.com/builds/500/motivewave_6.7.10_amd64.deb
-    sha512sums = c97e3bb78236d6ef1ae8581e29b128e6ee512f8241617dbcab5989f3068bfa6bbe9b9c091bb09b238ea891f59e6c12ef13ceee079610f3fc95722c58c4769bb9
+       source = motivewave-6.7.10.deb::https://www.motivewave.com/update/download.do?file_type=LINUX
+       sha512sums = c97e3bb78236d6ef1ae8581e29b128e6ee512f8241617dbcab5989f3068bfa6bbe9b9c091bb09b238ea891f59e6c12ef13ceee079610f3fc95722c58c4769bb9

 pkgname = motivewave
```

Also, in [61d4efc](https://aur.archlinux.org/cgit/aur.git/commit/?h=motivewave&id=61d4efc5898c57a8ab286e23fc393569b9a99a6), a `chown` command was modified to invalid syntax.

I'm not going to waste any more time reviewing your work.  You have until the end of the day (time zone of my choosing) to resolve these issues.

**Comment by xiota** [comment]
`motivewave` has been dropped for following reasons:

* Maintainer did not fix issues after multiple requests.
  - `.SRCINFO` was manually edited
  - `PKGBUILD` contains syntax error
* Package is a duplicate of `motivewave-latest-bin`

This package will *not* be reconsidered for inclusion in chaotic-aur.

Users are encouraged to use `motivewave-latest-bin` instead.  Those who prefer `motivewave` are free to build it themselves.

**Comment by xavierbaez** [comment]
You’re like a politician

Vote for me
Vote for me

I already told you the suggestions showed didn’t change the other file

And it’s more like your package is a duplicate of my package 📦

but whatever, you came to AUR and instead of letting both packages co-exist, you found a way to re-delete me twice

pathetic

**Comment by xiota** [comment]
@xavierbaez Standard inclusion criteria were relaxed to give you a chance to keep the package available through the chaotic-aur repositories.  The only requirement was that you keep it maintained.  Yet, despite repeated requests to fix issues, and warning that failure to do so could be grounds for its removal, you did not maintain the package.

Your claim about the nature of the differences between the manually and autogenerated `.SRCINFO` is inaccurate.  Regardless, manually editing `.SRCINFO` is not acceptable.

There is no legitimate reason for syntax errors in `PKGBUILD`.

Any package with the similar issues and an uncooperative maintainer would be a candidate for removal.

**Comment by xavierbaez** [comment]
motivewave works with makepkg
motivewave-latest -bin does not work

https://wiki.archlinux.org/title/makepkg
Why on earth are you so obsessed with being the maintener of motivewave?
You claim this was reason for deletion, yet your own package doesn't comply.

**Comment by xavierbaez** [comment]
> `motivewave` has been dropped for following reasons:
> 
>     * Maintainer did not fix issues after multiple requests.
>       
>       * `.SRCINFO` was manually edited
>       * `PKGBUILD` contains syntax error
> 
>     * Package is a duplicate of `motivewave-latest-bin`
> 
> 
> This package will _not_ be reconsidered for inclusion in chaotic-aur.
> 
> Users are encouraged to use `motivewave-latest-bin` instead. Those who prefer `motivewave` are free to build it themselves.

Your package doesn't work with that package either.
This is crazy you delete my package and don't even check your package.

**Comment by xavierbaez** [comment]
Why don't you go read https://wiki.archlinux.org/title/PKGBUILD
and test this against your package???

"Users are encouraged to use motivewave-latest-bin instead. Those who prefer motivewave are free to build it themselves."

Oh, how convenient to delete my package when your package doesn't work with makepkg.

You are a very unfair person.
