### ISSUE TITLE
pamac-all ban

### ISSUE THREAD

**Issue by bphd** [chaotic-aur/packages#2800]
patlefort [1] added the following comment to pamac-all [2]:

The chaotic-aur is missing `pamac-cli`, `pamac-all` and `libpamac-
full`, you should report this problem to them. Until then, `pamac-aur`
will be picked over `pamac-cli` by your aur helper because it
prioritize built packages over the AUR and it claim to provide `pamac-
cli`.

**Comment by Technetium1** [comment]
@dr460nf1r3 [it's from this comment on AUR](https://aur.archlinux.org/packages/pamac-all#comment-934455)

@bphd We will not ever build `pamac-all` because it depends on `libpamac-full`, which depends on `snapd`. For more details see https://github.com/chaotic-aur/packages#banished-and-rejected-packages-

**Comment by xiota** [comment]
Looks like there are issues with `pamac-all` caused by adding a depends on `pamac-cli`, which is provided by `pamac-aur`, which conflicts with `pamac-all`.  The maintainer is blaming it on chaotic-aur, but the `pamac-*` packages are built without interfere.

The issue is caused by `depends`, `provides`, `conflicts` directives in the `PKGBUILD`s.  Normally, when `pamac-aur` is not in an installed repository, the issue is not triggered because AUR helpers would prefer to use the named package directly (`pamac-cli`).  But some AUR helpers might prefer packages in repositories.  So if chaotic-aur is installed, `pamac-aur` becomes preferred.

To avoid the issue, `yay` users can try `--aur` or `--ignore` options.  Other AUR helpers may or may not have similar options.

See discussion on aurweb comments for `pamac-all` starting from: patlefort commented on [2023-08-06 19:46 (UTC)](https://aur.archlinux.org/packages/pamac-all?O=10#comment-928108).
