### ISSUE TITLE
[Request] voicevox-appimage

### ISSUE THREAD

**Issue by bibliothec** [chaotic-aur/packages#2827]
### Package:

https://aur.archlinux.org/packages/voicevox-appimage

### Purpose:

speech synthesis software ( free text-to-speech software )

### Benefits:

Announcements, video creation, etc using Japanese

### Copyright:

custom (Partly open source)

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Missing dep, left [a comment for maintainer](https://aur.archlinux.org/pkgbase/ppsspp-git#comment-936731).

**Comment by xiota** [comment]
@Technetium1 Think you left comment on wrong package?

`aur/voicevox-appimage` does depend on `appimagetool`.  It unpacks, modifies, and repacks the Appimage.  I prefer packages that leave AppImages unpacked in `/opt` because they perform better.

The AppImage takes up about 2GB. Since it's downloaded in parts, unpacked, repacked, packaged, I'd expect this package to use about 12GB to build.  (2GB parts → 4GB unpacked → 2GB repacked → 2GB pkg → 2GB pkg.tar.zst)

**Comment by Technetium1** [comment]
@xiota definitely did go to the wrong tab for the comment, fixed it, thank you! I wasn't sure of the size yet. If it *IS* 2GB, then this is going to be declined.

**Comment by xiota** [comment]
File sizes can be reviewed at https://github.com/VOICEVOX/voicevox/releases
