### ISSUE TITLE
[Remove davinci-resolve

### ISSUE THREAD

**Issue by NerosTie** [chaotic-aur/packages#2832]
### Packages:

https://aur.archlinux.org/packages/davinci-resolve

### Latest chaotic version

18.1.4-1.2

### Reason for rebuild

The package is outdated in chaotic-aur.

chaotic-aur: 18.1.4-1.2
aur: 18.6.0-3

**Comment by xiota** [comment]
`davinci-resolve` and `davinci-resolve-studio` seem to be broken:

* PKGBUILDs use `jq` before it's installed to satisfy `makedepends`
* `patchelf` fails because cannot find paths before they're installed
* Other minor issues

Kind of complicated for interfere, and don't really feel like convincing maintainer to fix.

Wondering if they should just be dropped.  They're each about 3GB, and take about 21GB to build.  (3GB zip → 3GB appimage → 6GB squashfs → 6GB pkg → 3GB pkg.tar.zst)

**Comment by dr460nf1r3** [comment]
I'd be fine with this, especially due to the issues other than eating a lot of space 👍 is this a maintainer's pkg or a requested one?

**Comment by Technetium1** [comment]
@dr460nf1r3 it was originally recommended software in the Garuda Setup Assistant, and `davinci-resolve-studio` was requested in #488

**Comment by xiota** [comment]
On Debian, there are packages that download and install files from the user side.  They're usually to work around licensing and redistribution issues, but also resolve potential concerns with bandwidth and storage space.  Are there any such packages on Arch or AUR?  Would something like that work for chaotic-aur?
