### ISSUE TITLE
[Rebuild] nvidia features missing from fastgame-git

### ISSUE THREAD

**Issue by gardotd426** [chaotic-aur/packages#2901]
### Packages:

https://aur.archlinux.org/packages/fastgame-git

### Latest chaotic version

0.2.0.r18.g5273f9c-1

### Reason for rebuild

Your build of fastgame-git doesn't include libraries, which breaks Fastgame's Nvidia GPU control functionality. 

When building the package from the AUR, you get `/usr/lib/libfastgame_nvidia.so`, which gives you the `NVIDIA GPU` tab in Fastgame. 

![Screenshot_20231115_195512](https://github.com/chaotic-aur/packages/assets/54234607/45aa6b93-247a-43fd-bc7b-e4ca018c4601)

When using your package, you don't provide `/usr/lib/libfastgame_nvidia.so`, for some reason, and therefore Fastgame can't interact with the GPU:

![Screenshot_20231115_193544](https://github.com/chaotic-aur/packages/assets/54234607/972b6ae0-9a3e-4f96-a5d4-31a7dbee901d)

The PKGBUILD on the AUR is dead simple, it just builds it with `arch-meson` and installs it to the `${pkgdir}`. And I checked the `interferes` repo, fastgame isn't supposed to have its PKGBUILD modified in any way, but somehow your build is broken. 

### Builds?

building the AUR PKGBUILD with `makepkg -si` provides the correct files. 

AUR build after compiling and installing is at 0.2.0.r54.g082da85-1

**Comment by xiota** [comment]
Rebuild will not fix this.  Considering the accusations, should this package be dropped?

**Comment by gardotd426** [comment]
I'm not sure how rebuilding wouldn't fix, there has to be some edit of the
PKGBUILD. It takes like 10 seconds to build from the AUR, go ahead and
build the AUR package yourself and you'll see that
/usr/lib/libfastgame_nvidia.so is in the finished package. But with
chaotic's package its not.

The file is supposed to be present whether you have an Nvidia GPU or not,
it doesn't check for an NV GPU at compile time or anything.

**Comment by xiota** [comment]
@gardotd426  This problem cannot be fixed with a simple rebuild because the PKGBUILD has some issues.  Try [building this package is a clean chroot](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot) to see an example.

The Chaotic AUR build scripts automatically fix some common issues, so broken packages often still build.  However, this package does not include nvidia-specific dependencies, so the nvidia features are not built.

Also, the maintainer/developer [wrote](https://aur.archlinux.org/packages/fastgame-git#comment-933537):

> I have updated the master branch with some changes that should avoid the use of this header when libxnvctrl is not available.

**Comment by xiota** [comment]
Issue fixed with interfere.
