### ISSUE TITLE
[Request] anyrun-git

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2932]
### Package:

https://aur.archlinux.org/packages/anyrun-git

### Purpose:

A rust-based wayland native krunner-like runner

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by D3vil0p3r** [comment]
@xiota can you give a look to it?

**Comment by xiota** [comment]
Package itself looks okay, but I don't use wayland.  When I try running it in weston, nothing happens.

**Comment by D3vil0p3r** [comment]
In my case it seems working. @end-4 in your configuration anyrun-git works correctly too, right?

**Comment by end-4** [comment]
Built with the AUR package, then yes

**Comment by xiota** [comment]
Package missing provides/conflicts.  Currently inconsequential because there are no upstream releases and all existing plugins are included.

**Comment by D3vil0p3r** [comment]
Would you remove the package from Chaotic AUR?

**Comment by xiota** [comment]
> Would you remove the package from Chaotic AUR?

Are you requesting removal (eg, you don't need it anymore)?  Or are you asking whether missing provides/conflicts is a problem that could result in removal?  For the latter, depends multiple factors:

* How consequential the problem becomes.  Mainly whether it interferes with other packages.  Right now, leaving alone because it doesn't seem to matter.  The plugin packages are currently not useful.
* How difficult the maintainer is to convince to fix issues.
* How difficult problems are to fix.
* Whether another package is available.  Currently, there is no stable release.
* Number of users who may be affected.  Metrics currently 869.
* Possibly others.

Since metrics are so high, would most likely fix with interfere.  If too many new problems develop, may consider custom package.  If stable package becomes available (with fewer problems), may consider switching.

**Comment by xiota** [comment]
Switching to stable package because -git package fails to build, and aur maintainer hasn't responded to comments in a while.  This is upstream's first stable release.

Metrics anyrun-git 425.
