### ISSUE TITLE
[Request] wine-staging-wow64

### ISSUE THREAD

**Issue by sevenfzerox** [chaotic-aur/packages#2948]
### Package:

https://aur.archlinux.org/packages/wine-staging-wow64-git + interfere

### Purpose:

Wine compatibility layer, built in wow64 experimental mode, like existing #2635 but with staging patches.
Can run 32 bit programs without any 32 bit dependencies.

### Benefits:

Avoid to install 32 bit dependencies.

### Copyright:

LGPL

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Related #2635

**Comment by xiota** [comment]
I don't know what pkgconf is?

**Comment by xiota** [comment]
I didn't have a pkgconf issue, but git was missing.  Still building though.  If successful, it will be in the repo for testing.  The maintainer will need to fix some issues before I add it to the lists though.

**Comment by xiota** [comment]
Looks like build was successful... wine-staging-wow64 8.21-1... have fun.  When I notice the package is updated, I'll add it to the list.

**Comment by xiota** [comment]
`aur/wine-staging-wow64` is tracking release candidates.  To provide a  more stable experience, this package is being provided with `aur/wine-staging-wow64-git` + interfere.

**Comment by xiota** [comment]
`multilib/wine-staging` 10.8-2 will have wow64 mode enabled.  After the multilib package is out of testing, `wine-staging-wow64` will be converted to a metapackage to migrate users.  A new package may be created later to remove the left-over metapackages.

`wine-staging-wow64-git` will be replaced with a custom `wine-staging-git` package.  The -git package will eventually be dropped because new versions of wine-staging are released so frequently.

Metrics:

* wine-staging-wow64 # 552
* wine-staging-wow64-git # 119
