### ISSUE TITLE
[Bug] rpcs3-git doesn't update

### ISSUE THREAD

**Issue by pacifi5t** [chaotic-aur/packages#2954]
### Packages:

https://aur.archlinux.org/packages/rpcs3-git

### Latest chaotic version

`0.0.29.r380.g8ebb7b4-1`

### What happens?

The package in the repository is outdated and doesn't update itself along with the changes to the git repo.

### What is expected to happen?

The version in the AUR is `0.0.29.r15620.f398f1113d-1`. Since this is the `-git` package, the latest version after local build is `0.0.29.r15809.f8e0c9e27a-1` at the time of creating this issue. The version of the package in the chaotic repository should be the same as or newer than the version in the AUR.

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/rpcs3-git.log

**Comment by xiota** [comment]
There is nothing wrong with the version string on `chaotic-aur`.  It counts revisions since release, which is the method recommended in VCS package guidelines.  The version string of the `aur` package counts total commits.

That said, `rpcs3-git` was last built a few days ago (2023-12-12).  May be another ufscar issue.

**Comment by xiota** [comment]
Closing because seems to be building normally now.  Comment here if there are more issues related to this package.
