### ISSUE TITLE
[Request] cosmic-term-git

### ISSUE THREAD

**Issue by evansan** [chaotic-aur/packages#2996]
### Package:

https://aur.archlinux.org/packages/cosmic-term-git

### Purpose:

Cosmic terminal developed by System76

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
This is pre-alpha software that I would rather not add.  If you want to try it out, there is a recent build of `cosmic-epoch-git` in the repo.  If you think it is useful for more than checking development progress, describe use cases in which users would choose to use this pre-alpha terminal emulator instead of one with stable releases.

**Comment by Technetium1** [comment]
We can explore adding this in the future
