### ISSUE TITLE
[Request] ironbar-git

### ISSUE THREAD

**Issue by helixoid** [chaotic-aur/packages#3060]
### Package:

https://aur.archlinux.org/packages/ironbar-git

### Purpose:

This is a wayland status-bar written in rust.
This is a good replacement for waybar & works great with Hyprland.

### Benefits:

This is fairly new project and undergoes several changes so the git package would make more sense.

### Building:

makepkg

### Copyright:

MIT

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Switched to custom package a couple weeks ago because package was failing to build.  It already had an interfere, and updating it had become more troublesome than rewriting the package.  AUR package was subsequently fixed.  Leaving as a custom package for now.  Will consider switching back to AUR if it stays in a good state.  Metrics 165.
