### ISSUE TITLE
[Request] flutter-bin

### ISSUE THREAD

**Issue by hasanpasha** [chaotic-aur/packages#3088]
### Packages:

https://aur.archlinux.org/pkgbase/flutter-bin

~~https://aur.archlinux.org/pkgbase/flutter~~
~~https://aur.archlinux.org/pkgbase/flutter-artifacts-google-bin~~

### Purpose

Dart/Flutter development

### License

BSD-3-Clause, Google-Patent-Grant

### More information

`flutter`'s package `flutter-target-linux` depends on `flutter-engine-linux` which is not found in `chaotic-aur` repo causing unresolved dependencies, and the same for `flutter-target-android` and `flutter-target-web`

**Comment by xiota** [comment]
The maintainer is reorganizing / splitting the package.  I'll take a closer look later.  If it's too complicated, may replace with a monolithic package similar to how it was before.

**Comment by dr460nf1r3** [comment]
It seems it requires a second pkgbase to work, rather than having it all in one PKGBUILD: https://aur.archlinux.org/pkgbase/flutter-artifacts-google-bin
It's from the same maintainer, so that's likely the way to move forward. No other package provides the needed steps. I feel like this adds a shit ton of unneeded split packages, but hey.

**Comment by xiota** [comment]
There are comments with complaints about build failure.

I still want to review this when things settle... so reopening as a reminder.

**Comment by hasanpasha** [comment]
I was able to install the packages from the chaotic-repo successfully. Thanks for your quick fix.

**Comment by xiota** [comment]
@hasanpash In addition to installing flutter, does it also work as expected?

**Comment by hasanpasha** [comment]
@xiota It was working just fine when I wrote my comment above. Now after updating to version `3.19.6` I get the below error when running `flutter run` in any project:
```Unhandled exception:
Unexpected Kernel Format Version 117 (expected 114)
#0      BinaryBuilder.readComponent.<anonymous closure>
(package:kernel/binary/ast_from_binary.dart:692)
#1      Timeline.timeSync (dart:developer/timeline.dart:173)
#2      BinaryBuilder.readComponent
(package:kernel/binary/ast_from_binary.dart:679)
#3      _InitializationFromSdkSummary._prepareSummary
(package:front_end/src/fasta/incremental_compiler.dart:2503)
#4      _InitializationFromUri.initialize
(package:front_end/src/fasta/incremental_compiler.dart:2577)
<asynchronous suspension>
#5      IncrementalCompiler._ensurePlatformAndInitialize
(package:front_end/src/fasta/incremental_compiler.dart:1383)
<asynchronous suspension>
#6      IncrementalCompiler.computeDelta.<anonymous closure>
(package:front_end/src/fasta/incremental_compiler.dart:270)
<asynchronous suspension>
#7      CompilerContext.clear
(package:front_end/src/fasta/compiler_context.dart:139)
<asynchronous suspension>
#8      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:77)
<asynchronous suspension>
#9      FrontendCompiler.compile
(package:frontend_server/frontend_server.dart:610)
<asynchronous suspension>
#10     listenAndCompile.<anonymous closure>
(package:frontend_server/frontend_server.dart:1303)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
``` 
which is also reported in the AUR page [here](https://aur.archlinux.org/packages/flutter#:~:text=Trying%20to%20update%20to%203.19.6%2D1%20and%20I%20get%20the%20following%20whenever%20I%20flutter%20run%3A) .

**Comment by xiota** [comment]
The flutter package reorganization is too experimental, and the maintainer is planning more ¿breaking? changes.  I'm considering replacing it with a monolithic `flutter-bin` package that installs to `/opt/flutter` and uses helper scripts to run `unionfs-fuse` to make the folder "writable" so that flutter will function.

**Comment by xiota** [comment]
I'm considering dropping the split flutter, flutter-engine, etc packges (keeping flutter-bin) because they're too complicated and unreliable.  On my computer, I have to run pacman multiple times to install the depends in the right order.

@hasanpasha Someone has reported that the flutter packages work with `aur/dart-sdk-dev`.  The package is in chaotic-aur for testing.  Can you confirm whether flutter works when it's installed?  Do you have any opinion about split packaging vs monolithic flutter-bin?

**Comment by hasanpasha** [comment]
@xiota I am currently not on my system so I can't test whether this works or not, I will come back with the results as soon as I can. As for monolithic vs split packages, I think the split packages would be better for other flutter packages that depend on it, and it makes the installation cleaner.

**Comment by hasanpasha** [comment]
after full removal of `flutter` packages and `dart` with `sudo pacman -Rcus dart flutter` and installing flutter again with `dart-sdk-dev` I get the following error when running `flutter doctor` or any other flutter command:
```
Wrong full snapshot version, expected 'e626b3c974f4afdd82d77a14c5e59173' found 'ee1eb666c76a5cb7746faf39d0b97547'
```

**Comment by xiota** [comment]
@hasanpasha Thanks for testing.  I'm going to drop the split packages because they are not working.  Will reconsider adding them back when comments on the aur page indicate that it is working reliably.

**Comment by xiota** [comment]
The split `flutter`/`flutter-artifacts-google-bin` packages will not be added back unless the patches they are based on are upstreamed back to Google.  The problem is whenever they're updated, the various components, including `extra/dart`, go out of sync within days, making the collection useless.

I've repurposed this issue to track `flutter-bin`.  Another useful package to consider is `fvm`.
