### ISSUE TITLE
[Rebuild] `wine-tkg-fsync-git`

### ISSUE THREAD

**Issue by dreirund** [chaotic-aur/packages#3165]
### Packages:

Not in the AUR.

### Latest chaotic version

`9.8.r117.ge6e1bbb4109-327`

### Reason for rebuild

`wine-git` currently is at version `9.9.r50.gd41a1f0183f`.

This should catch up.

**Comment by xiota** [comment]
I think the `wine-tkg-*` packages should be dropped.  As far as I can tell, they're run by [special routine](https://github.com/chaotic-aur/toolbox/blob/main/src/lib/routines-tkg-wine.sh) in toolbox.

```
==> ERROR: Patch application has failed. The error was logged to /home/main-builder/pkgwork/prepare.log for your convenience.
```

**Comment by xiota** [comment]
Dropped the `wine-tkg` packages.  Seems they already haven't been built in a while.

More wine packages may be dropped later because they use a lot of bandwidth and often don't quite work.   Many programs need specific versions of wine, so it makes more sense to use a program to manage wine instances than to try to use a system install.
