### ISSUE TITLE
[Request] proton-vpn-gtk-app

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#3167]
### Package:

https://aur.archlinux.org/packages/proton-vpn-gtk-app

### Purpose:

Protonvpn gui app

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by dr460nf1r3** [comment]
I have a feeling that this contradicts this action here: https://github.com/chaotic-aur/packages/commit/cddcf8f21ffbbd230ffd81adeba6a4bf13ea4b6d

@Technetium1

**Comment by Technetium1** [comment]
Thanks for opening this request.

I'm not particularly comfortable adding this in due to the current state of the application. Arch is no longer an official target to be tested against or supported. They seem to have fired whoever was in charge of it before, and have posted (and pinned) [a comment about a related job listing](https://aur.archlinux.org/packages/protonvpn-gui#comment-941297) on the previously abandoned package, which I personally find distasteful. This has many dependencies, and quite frankly I don't trust it to be an acceptable VPN client implementation in the first place. This includes distrusting the actual abilities **_NECESSARY_** for clients to be secure, such as killswitch functionality. Not linking issues together; but I can even see an open issue for killswitch failure in https://github.com/ProtonVPN/proton-vpn-gtk-app/issues.

Even if they did a somewhat trustworthy implementation, then we still have the issue of Arch _never_ being tested against officially (or even designed for). I don't trust the community to constantly independently verify that the application is working (or compiling) as it should be, and Proton sure isn't doing it either! Until there are major changes at Proton, this is denied.
