### ISSUE TITLE
[request]  BombSquad

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#320]
## BombSquad
AUR : https://aur.archlinux.org/packages/bombsquad/
Lutris : https://lutris.net/games/bomb-squad/
Builds : https://files.ballistica.net/bombsquad/builds/
## BombSquad Community Mod Manager
Github : https://github.com/Mrmaxmeier/BombSquad-Community-Mod-Manager

**Comment by PedroHLC** [comment]
Adopted, thanks for your contribution.

**Comment by xiota** [comment]
Looks like a cool game, but dropping because it has likely broken numerous times without anyone noticing.  If no one actually uses it, there's no point trying to keep it functional.

The upstream host rebuilds without bumping version or changing filename, producing hash mismatches.  Program doesn't run without old python version (currently `python312`, so hasn't been usable for a month).

Metrics 5.
