### ISSUE TITLE
[Request] upg

### ISSUE THREAD

**Issue by Xatra1** [chaotic-aur/packages#3212]
### Package:

https://aur.archlinux.org/packages/upg

### Purpose:

This script automates upgrades with various package managers such as apt, Pacman, dnf, and distro agnostic managers like Flatpak, Snap, and npm. Other QoL tasks are also performed like initramfs rebuilding, cache clearing and removal of the user's trash. If plocate(1) is installed, it will also update the filesystem index used by it. If the user does not have the necessary commands to perform an upgrade (For example, not having apt), then that piece of the script will simply be skipped, allowing the script to work in different environments.

### Building:

makepkg -si

### Copyright:

GPL3

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
This feels particularly unsafe:
https://github.com/Xatra1/upg/blob/b6c580dc68b0f549cca434345193d319bb1d5ba5/upg#L216-L217

Why not checksums? https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=upg#n16

**Comment by xiota** [comment]
Inclined to reject because I don't see the point.  This looks like a personal system maintenance script.  Potential users should write their own, based on their own needs.

Following list of problems is not exhaustive:

* The entire routine and options are hard coded.  For example, no way for a user to check and upgrade only flatpak packages.
* Runs tasks that users may not want:
    - clear cache
    - empty trash
    - modify grub and initramfs – Could make system unbootable with no benefit because standard package managers typically already perform these as needed.
    - routinely delete pacman lockfile – could cause significant damage to system.
* Makes runtime assumptions that don't necessarily hold.  Potentially unintentionally altering system files.
* Maybe others.

**Comment by dr460nf1r3** [comment]
Besides, there is topgrade serving the same purpose as far as I'm aware 🤔
