### ISSUE TITLE
[Request] cosmic-session-git

### ISSUE THREAD

**Issue by JamesClarke7283** [chaotic-aur/packages#3217]
### Package:

https://aur.archlinux.org/packages/cosmic-session-git

### Purpose:

Its the Cosmic Desktop environment, and the most uptodate package for it on the AUR.

### Benefits:

Unlike cosmic-epoch-git, this package is actually uptodate.

### Building:

makepkg -si

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
v3 builder is down, so no point adding new packages.  v4 builder should be ready "soon".

I would prefer to provide only the epoch package until the software is actually released.  Not interested in (slippery slope of) adding a couple dozen packages because someone's favorite component isn't updated enough.

**Comment by Technetium1** [comment]
This is complex enough that I'd rather provide on v4 instead

**Comment by xiota** [comment]
Is this package still needed now that `extra/cosmic-session` is available?

@fabianski7 @Daktyl198 Thoughts?

**Comment by xiota** [comment]
Thanks.  That's good to know.  Will try to keep the package available until there is a "real" release.
