### ISSUE TITLE
[Request] linux-xanmod-linux-bin-x64v2

### ISSUE THREAD

**Issue by Ravi-Kishor** [chaotic-aur/packages#3218]
### Package:

https://aur.archlinux.org/pkgbase/linux-xanmod-linux-bin-x64v2

### Purpose:

Its an optimized version of xanmod specially for older cpus. and Imagine compilation time on my old 2nd gen laptop. Please be kind and add these 2 packages.

### Benefits:

Its an optimized version of xanmod specially for older cpus.

### Building:

![Screenshot from 2024-07-08 13-27-52](https://github.com/chaotic-aur/packages/assets/97280268/4f71e09f-97d8-47e7-95cf-7f5086f5a0c3)

### Copyright:

GPL3

### Expected Interest:

Only me

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
We did drop v2 intentionally...
https://github.com/chaotic-aur/packages/issues/2242#issuecomment-2184600331
https://github.com/chaotic-aur/packages/issues/3199#issuecomment-2176531037

**Comment by xiota** [comment]
I dropped the v2 packages because of low usage, but high resource requirements to build.  Majority of users should be using v2 or v3 kernels, but don't.  Would be reasonable to bring back a v2 kernel if user awareness / usage could be improved.

Current metrics: 2465 - linux-xanmod, 97 - linux-xanmod-v3.

**Comment by Pakrohk** [comment]
I am confused, how can bin packages have a lot of processing for you? These packages are pre-made
Please explain first.

If possible, please add the [LTSx64v2](https://aur.archlinux.org/packages/linux-xanmod-lts-linux-bin-x64v2) packages and its [headers](https://aur.archlinux.org/packages/linux-xanmod-lts-linux-headers-bin-x64v2).

**Comment by xiota** [comment]
Kernel packages currently available on chaotic-aur are built from source.  Unless there is some problem, packages that build from source are preferred over bin packages.  Most bin packages can be made directly by users with minimal effort.

I'm still thinking about reintroducing a v2 kernel package, but would build from source.

**Comment by Ravi-Kishor** [comment]
> If possible, please add the [LTSx64v2](https://aur.archlinux.org/packages/linux-xanmod-lts-linux-bin-x64v2) packages and its [headers](https://aur.archlinux.org/packages/linux-xanmod-lts-linux-headers-bin-x64v2).

anyways Xanmod V1 looks depreciated shifting to V2 for lts and mainline would be a great decision.

**Comment by Pakrohk** [comment]
![image](https://github.com/user-attachments/assets/efab567c-05a5-4ffe-b705-fd7600bc499b)


> > If possible, please add the [LTSx64v2](https://aur.archlinux.org/packages/linux-xanmod-lts-linux-bin-x64v2) packages and its [headers](https://aur.archlinux.org/packages/linux-xanmod-lts-linux-headers-bin-x64v2).
> 
> anyways Xanmod V1 looks depreciated shifting to V2 for lts and mainline would be a great decision.

yes

**Comment by xiota** [comment]
Planning to reorganize linux-xanmod packages.

* linux-xanmod-edge-v3
* linux-xanmod-v2
* linux-xanmod-lts
* linux-xanmod-rt

May change v2/v3 suffices to something more descriptive, like x64v2/x64v3.

Rationale: Minimal benefit building multiple versions of each kernel because linux-xanmod-edge and linux-xanmod are out of sync for only about a month after kernel version is bumped.  Users with "newer" hardware (v3) are more likely to benefit from latest kernel releases (edge).  Users with old hardware (v1) are unlikely to benefit from newest kernel releases, so lts should be sufficient.  Leaving rt kernel alone.

**Comment by xiota** [comment]
Reorganization in progress... Related #2242
