### ISSUE TITLE
[Request] fooyin

### ISSUE THREAD

**Issue by theblu3j** [chaotic-aur/packages#3219]
### Package:

https://aur.archlinux.org/packages/fooyin

### Purpose:

Fantastic new QT based music player. Takes inspiration from foobar2000, but is open source.

### Benefits:

Foobar2000 runs through wine, Fooyin does not

### Building:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fooyin
makepkg -si

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Considering adding interfere or switching to custom package to avoid depends on `libvgm-player-git`.  Better for stable packages to avoid `-git` depends.

**Comment by theblu3j** [comment]
With the limited knowledge I have, I looked through the Fooyin CI page jobs and it looks like there is a [job](https://github.com/fooyin/fooyin/actions/runs/10586857249/job/29336459735) set up for Arch but nothing is being produced (yet?). There is also fooyin-bin already on the AUR using the `.deb`.

**Comment by xiota** [comment]
The problem is `aur/fooyin` fails to build because relatively new depends on `aur/libvgm-player-git`.  Since it's better for stable packages to not depend on git packages, I'm considering modifying the package.  Nothing else uses libvgm, so there's no benefit keeping it as a separate package.

Alternatively, could switch to `aur/fooyin-git`.

**Comment by xiota** [comment]
Decided to switch to `fooyin-git`.
