### ISSUE TITLE
[Request] pcloud-drive

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#3246]
### Package:

https://aur.archlinux.org/packages/pcloud-drive

### Purpose:

Official app for the pcloud storage platform

### Copyright:

custom - not exactly sure what

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

81 votes, popularity 0.88 at the time of writing.

**Comment by xiota** [comment]
Electron 3.1.11.
```
$ strings -a pcloud | grep -Pom1 'Electron/\S+'
Electron/3.1.11
```

**Comment by coxackie** [comment]
> Electron 3.1.11.
> 
> ```
> $ strings -a pcloud | grep -Pom1 'Electron/\S+'
> Electron/3.1.11
> ```

Is this a problem? I know it is ridiculously old version, but it does not require electron installed.

**Comment by Technetium1** [comment]
Yes, it is a problem. That's **way** too old! It doesn't require it to be installed because it is embedded. [Apparently they've known this was an issue for years now](https://aur.archlinux.org/packages/pcloud-drive#comment-877700) according to the (somewhat concerning) pinned comment. I'm not inclined to further consider adding this package whatsoever until that is sorted.

**Comment by xiota** [comment]
Packages related to obsolete electron versions have some major problems:

* Upstream project essentially unmaintained.
* Bugs and security holes will never be fixed.  Electron 3 was EOL in 2019.
* Packages often unbuildable, not working, stop working, etc.  Waste of effort to fix.
