### ISSUE TITLE
[Request] linux-lts515

### ISSUE THREAD

**Issue by thomasongwae** [chaotic-aur/packages#3274]
### Package:

https://aur.archlinux.org/packages/linux-lts515/

### Purpose:

new kernels are having problems with my old laptop graphics card

### Copyright:

GPL#

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Most kernel packages need interfere for clean up, but this one seems quite different from the others.  For example, it supports multiple CARCH and apparently has docs disabled, but still creates the docs package?

What graphics card are you using?

**Comment by thomasongwae** [comment]
very old graphics card NVA8 (GT218)

**Comment by xiota** [comment]
Interfere: https://github.com/chaotic-aur/interfere/tree/master/linux-lts515

**Comment by xiota** [comment]
Since `linux-lts515` has been reasonably trouble-free, adding `linux-lts61` and `linux-lts66` in case someone finds them useful.  Users should be aware that they may not be usable on systems requiring features from newer kernels (eg, file system).  Will not add kernels < 5.15 without sufficient justification.  Metrics:

* linux-lts515 # 53
* linux-lts515-headers # 46
