### ISSUE TITLE
[Rebuild] lib32-x265

### ISSUE THREAD

**Issue by antermin** [chaotic-aur/packages#3278]
### Packages:

https://aur.archlinux.org/packages/lib32-x265

### Latest chaotic version

`3.5-2`

### Reason for rebuild

Outdated - the latest version is `3.6`, however the package in AUR has not been updated for a long period, and is already flagged as out-of-date for 2 months.

A manual update of `lib32-x265` in Chaotic-AUR is desirable, since the latest release of `lib32-ffmpeg` cannot be built properly ([Chaotic-AUR log for lib32-ffmpeg](https://builds.garudalinux.org/repos/chaotic-aur/logs/lib32-ffmpeg.log)) with mismatching `x265` and `lib32-x265` versions.

**Comment by xiota** [comment]
Rebuilt.
```
lib32-x265 3.6-1
lib32-ffmpeg 2:7.0.2-1
```

**Comment by xiota** [comment]
The problem is I haven't been convinced that they're useful relative to the effort that's been required to keep them functional.  Also, "sometime next month" is whenever the switch to v4 build system occurs, so could be longer.

WINE has a new wow64 mode that can run 32-bit binaries without `lib32-` packages.  Search the repo for "wow64" to try the packages that have it enabled.
