### ISSUE TITLE
[Request] zen-browser-bin

### ISSUE THREAD

**Issue by Ast3risk-ops** [chaotic-aur/packages#3290]
### Package:

https://aur.archlinux.org/packages/zen-browser-bin

### Purpose:

Zen Browser is basically Arc but Firefox, makes Firefox more modern, more beautiful, more private (includes some BetterFox patches), ~~and faster~~.

It has workspaces, themes, and vertical tabs for instance.

### Benefits:

~~It's way faster than Firefox and more beautiful and customizable than Firefox.~~ Also more private through said BetterFox patches.

### Building:

Run `makepkg -si`, which will download the latest prebuilt `zen.linux-specific.tar.bz2` and extract the files to the right folders. Disables the builtin updater through a `policies.json`.

### Copyright:

MPL-2.0

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Website: https://zen-browser.app
Github: https://github.com/zen-browser/desktop
Stars: 10.1k

~~This version is optimized for newer AVX2 processors.~~

There is also a generic version for older machines, [`zen-browser-bin`](https://aur.archlinux.org/packages/zen-browser-bin) though my request centers on the AVX2 version.

**Comment by xiota** [comment]
I prefer avoiding -bin browser packages, but suppose it would be fine if different enough from other firefox forks.

Have you benchmarked the two versions to confirm that there is actually performance benefit from avx2?

**Comment by Ast3risk-ops** [comment]
> I prefer avoiding -bin browser packages, but suppose it would be fine if different enough from other firefox forks.
> 
> Have you benchmarked the two versions to confirm that there is actually performance benefit from avx2?

Zen has done their own benchmarks, I don't know what the default Firefox scores are.

https://docs.zen-browser.app/benchmarks

**Comment by xiota** [comment]
I mean avx2 vs standard build.  Have to run benchmarks multiple times to get low, same error margins.

In my past testing for other forks, optimizing for instruction set doesn't make any significant difference for firefox and chromium based browsers.  Most likely they already include multiple optimization targets in critical paths.

**Comment by Ast3risk-ops** [comment]
> I mean avx2 vs standard build. Have to run benchmarks multiple times to get low, same error margins.
> 
> In my past testing for other forks, optimizing for instruction set doesn't make any significant difference for firefox and chromium based browsers. Most likely they already include multiple optimization targets in critical paths.

No I haven't checked

**Comment by Ast3risk-ops** [comment]
> I mean avx2 vs standard build. Have to run benchmarks multiple times to get low, same error margins.
> 
> In my past testing for other forks, optimizing for instruction set doesn't make any significant difference for firefox and chromium based browsers. Most likely they already include multiple optimization targets in critical paths.

On my flawed test environment:

Clean tar.gz generic: 10.5

Maybe not-so-clean AUR package Optimized: 10

**Comment by xiota** [comment]
The ± errors are important.  Suppose generic is 10.5 ± 0.25 and optimized is 10 ± 0.25.  That would mean generic performs *significantly* better than optimized because the ranges do not overlap.  But if the results were 10.5 ± 0.65 and 10 ± 0.65, there is overlap, so there is "no significant difference".

I saw that a lot.  When testing Firefox/Chromium forks with everything the same except microarchitecture optimization, the generic build often had same or slightly "better" results, but still not significantly different.  If you check the instruction sets contained by the generic build (easiest is with `intelxed`), you'll find it already contains AVX/AVX2 instructions ⇒ they already include instruction set optimization in the build process.

**Comment by Ast3risk-ops** [comment]
@xiota Yeah, but I personally notice a decent different compared to normal firefox, and the extraction/compression process can take a while depending on the computer.

**Comment by BinaryHarbinger** [comment]
Hi there I'm just commenting to support the request flatpak version basically sucks and who wants to compile whole browser in their system (except that Gentoo guys)

Basically zen browser has lot of things to talk like vertical tabs and faster web engines. That is why we want it in Chaotic Aur

**Comment by xiota** [comment]
I'll run benchmarks between `zen-browser-avx2-bin` and `zen-browser-bin`.  If I don't see consistent significant difference, will add `zen-browser-bin`.

**Comment by xiota** [comment]
Methodology:

1. Build and install package
2. Run browser, create default profile
3. Run Speedometer 2.1 at least twice.  Repeat until error/sd is less than 2.

Note: Using Speedometer 2.1 instead of 3.0 so results can be compared with previous runs on different browsers.

Results: No significant difference between standard and avx2 versions of zen browser.  (The ranges overlap.)  Meanwhile, plain firefox from Arch repos is significantly faster.  (The ranges do not overlap.)

* firefox 121.0 — 86.6±1.8 (old)
* firefox 122.0 — 87.9±1.9 (old)
* firefox 130.0 — 91.3±1.6 (new)
* zen-browser-bin 1.0.0.a.39 — 79.3±1.2 ⇒ 78.1-80.5
* zen-browser-avx2-bin 1.0.0.a.39 — 80.8±1.4 ⇒ 79.4-82.2

**Comment by code-IM-perfect** [comment]
> Meanwhile, firefox from Arch repo and floorp 11.18.0 from Chaotic AUR repo are significantly faster.

So according to benchmarks, zen is slower than the stock firefox? Cuz it did feel snappier to use...may have been a placebo

(Sorry for replying on a closed issue but I really needed to know)

**Comment by Ast3risk-ops** [comment]
> > Meanwhile, firefox from Arch repo and floorp 11.18.0 from Chaotic AUR repo are significantly faster.
> 
> So according to benchmarks, zen is slower than the stock firefox? Cuz it did feel snappier to use...may have been a placebo
> 
> (Sorry for replying on a closed issue but I really needed to know)

The current website benchmarks are also out of date (as are xiota's benchmarks), new versions have come out.

**Comment by xiota** [comment]
The request was approved, with adjustment, based on the alternate interface, not potential performance difference.  Although rendering and script execution may not be faster, interface differences can make the overall experience feel better.

I'm not rerunning benchmarks.  While newer AVX2 versions could be faster than previous versions, so would newer non-AVX versions and newer Firefox versions.  Even if future benchmarks do show significant differences, I would not expect practical difference.  (The differences that matter are between different builds of the same browser.)
