### ISSUE TITLE
[Request] linux-mainline

### ISSUE THREAD

**Issue by eatmyvenom** [chaotic-aur/packages#331]
Very similar to the other issue I opened at #318 I would like to request the kernel mainline branch also is added to this repository.

Aur page
https://aur.archlinux.org/packages/linux-mainline

I would like to note that while miffie (the maintainer) does provide a repo where this package is built, it has the drawback that the server goes down from time to time and had therefore proven to be unreliable.

This package is updated by upstream about weekly therefore can be put into whatever time slot you really want.

**Comment by romanstingler** [comment]
@dr460nf1r3 can we get a v3 build for this one ?

**Comment by xiota** [comment]
What would be involved / required for a v3 repo?

**Comment by dr460nf1r3** [comment]
The -v3 kernels we currently provide are either built from dedicated PKGBUILDs or dynamically via a custom routine (tkg-kernels). So either needs to be in place for this to work out.

**Comment by xiota** [comment]
Switching `linux-mainline` to `linux-v3`, based on `core/linux`, because:

* `aur/linux-mainline` tracks tagged releases, so basically duplicating `core/linux`
* `aur/linux-mainline` builds from git, which is excessively resource intensive.  Linux kernels failing to build because running out of space.

**Comment by xiota** [comment]
My mistake... restored `linux-mainline` an updated v3 interfere.
