### ISSUE TITLE
[Request] the-honkers-railway-launcher-bin

### ISSUE THREAD

**Issue by Darian1999** [chaotic-aur/packages#3317]
### Package:

https://aur.archlinux.org/packages/the-honkers-railway-launcher-bin

### Purpose:

A launcher for a specific anime game with auto-patching, discord rpc and time tracking

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Inclined to reject because... Fighting against devs who are actively against Linux support is futile.

`aur/anime-games-launcher-bin` is already provided.  When it stops working, it should be dropped without replacement for reason stated above.  Similarly, launchers for some other games should also be dropped.
