### ISSUE TITLE
[Request] pcmanfm-qt-git

### ISSUE THREAD

**Issue by kRHYME7** [chaotic-aur/packages#3348]
### Package:

https://aur.archlinux.org/packages/pcmanfm-qt-git

### Purpose:

File manager and desktop icon manager (Qt port of PCManFM and libfm) 

### Benefits:

It has a good desktop icon manager support for wayland.  This is much helpful for the TWM users.  

### Copyright:

GPL2

### Expected Interest:

Many

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Stable package is available in `extra`.  What are benefits of the git package over stable?

If there isn't sufficient benefit, I would prefer not to add this package because building requires git versions of libraries that are often incompatible with the stable version, requiring other lxqt package to also be advanced to the git version.  Pace of lxqt development is fast enough that it's not really worthwhile for anyone not involved in development to bother building from git.

**Comment by xiota** [comment]
Rejecting for aforementioned reasons.
