### ISSUE TITLE
[Rebuild] whisper.cpp

### ISSUE THREAD

**Issue by dreirund** [chaotic-aur/packages#3360]
### Packages:

https://aur.archlinux.org/packages/whisper.cpp

### Latest chaotic version

`1.6.2-1`

### Reason for rebuild

Outdated since 10 days (version 1.7.1, currently `$pkgrel` -2)

**Comment by xiota** [comment]
I plan to look at this package sometime this week or weekend.

**Comment by BEST8OY** [comment]
I tried whisper.cpp a week ago and it was okay
https://builds.garudalinux.org/logs/logs.html?timestamp=1729842624626&id=whisper.cpp
Now it's 
```
whisper.cpp: error while loading shared libraries: libggml.so: cannot open shared object file: No such file or directory
```

**Comment by xiota** [comment]
@BEST8OY Are you using version 1.7.1-2?  The plain cpu version works on my computer.  I have not tried any of the others.  No package provides `libggml.so`.  Don't know why it would be needed.

**Comment by BEST8OY** [comment]
@xiota 
I installed ```libggml-git``` from AUR.

**Comment by xiota** [comment]
`aur/libggml-git` has some problems.  The most serious is that it detects cpu features (on the build machine) prior to building, which will cause the resulting binaries to throw illegal instruction errors on users' machines.  The following changes would be needed.  Otherwise, it would have to be rewritten and added as a custom package.

* Use standard pkgver format, as described and exemplified in VCS package guidelines.
* Remove CPU detection and build for baseline x86-64.
* Use `cmake` to call build and install commands.  Don't call `make` directly.

`llama.cpp` and `whisper.cpp` also do not declare the dependency.  They would need to be adjusted with interferes.

**Comment by xiota** [comment]
Interfere added to `whisper.cpp` in 902f713e13c296ddd22e818edce7a1ad47a16266, 2728a866145005b268f60f86a72d9b92791c98a4.  Interfere for `llama.cpp` pending.

**Comment by xiota** [comment]
Interfere for `llama.cpp` added in 571518779fa3ad6fca467ec3cba0e1e3fe6a9686

**Comment by xiota** [comment]
Appears `whisper.cpp` variants don't all work with `libggml-git`.  AUR maintainer has been notified via comment.  If package is not revised, will switch to custom packages with static linking.  May drop GPU variants.
