### ISSUE TITLE
[Request] pacman-static

### ISSUE THREAD

**Issue by xXPerditorXx** [chaotic-aur/packages#3386]
### Package:

https://aur.archlinux.org/pkgbase/pacman-static

### Purpose:

Statically-compiled pacman to fix or install systems without libc

### Benefits:

- Recovery for broken packages (e.g. openssl, libcrypto, or pacman itself)
- No dependence on shared libraries

### Copyright:

GPL-2.0-or-later 

### Expected Interest:

Some

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

### More information:

Already saved me multiple times, because openssl and libcrypto were somehow broken

**Comment by xiota** [comment]
I don't see a strong use case for providing static pacman.  Arch Linux keeps `core/pacman` working.  In most cases where it might fail, like installing custom glibc, the shell and other essential utilities would also become non-functional, so recovery disc would still be needed.

Also, package was previously dropped because of `shfmt` error `PKGBUILD:59:65: invalid UTF-8 encoding`.  Related #2207.

**Comment by dr460nf1r3** [comment]
> I don't see a strong use case for providing static pacman.  Arch Linux keeps `core/pacman` working.  In most cases where it might fail, like installing custom glibc, the shell and other essential utilities would also become non-functional, so recovery disc would still be needed.
> 
> Also, package was previously dropped because of `shfmt` error `PKGBUILD:59:65: invalid UTF-8 encoding`.  Related #2207.

You'd still be able to use TTY or am I mistaken? I'd be in favor of adding it given it no longer errors out.

**Comment by xiota** [comment]
> You'd still be able to use TTY or am I mistaken?

If the default shell (`bash`) doesn't work, user would be greeted with some error after login.  Would need some stack of statically compiled programs that are configured so that they actually work when needed.  Every Linux user should have the disc/USB/whatever used to install the system in the first place.

Package still has the `shfmt` error.  I have not interacted with the maintainer before, but this type of problem is potentially difficult to convince someone to change.
```
$ shfmt -w PKGBUILD
PKGBUILD:58:65: invalid UTF-8 encoding
```

**Comment by xiota** [comment]
Rejecting because invalid encoding would break the build system (recently demonstrated by another package).  Also, I'm not convinced it would be actually useful.
