### ISSUE TITLE
[Request] tinkerwell

### ISSUE THREAD

**Issue by anasgets111** [chaotic-aur/packages#3405]
### Package:

[Tinkerwell](https://aur.archlinux.org/packages/tinkerwell)

### Purpose:

It's a very good playground for laravel/php

### Benefits:

will benefit those using laravel/php

### Copyright:

Proprietary License

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

Yes

**Comment by xiota** [comment]
The purpose/benefits in request doesn't explain what this program is or does.  From the website, looks like an IDE/code editor for PHP.

Program is proprietary, closed source.  Package is based on appimage.

Request is rejected because the [EULA](https://tinkerwell.app/eula) does not permit redistribution.

> **You agree not to**, and You will not permit others to: License, sell, rent, lease, assign, **distribute**, transmit, host, outsource, disclose or otherwise commercially exploit **the Application or make the Application available to any third party.**
