### ISSUE TITLE
[Request] softmaker-office-nx-bin

### ISSUE THREAD

**Issue by DeN-AlB** [chaotic-aur/packages#3434]
### Package

https://aur.archlinux.org/packages/softmaker-office-nx-bin

### Purpose

Proprietary office suite; word processing, spreadsheets, presentations (subscription version)

### License

LicenseRef-custom

### Submission checklist

- [X] The package is not banned.
- [X] The package is not available in Chaotic AUR or official Arch repos.
- [X] The package has not already been requested.

**Comment by Technetium1** [comment]
@DeN-AlB Why this instead of `softmaker-office-2024-bin`? https://github.com/chaotic-aur/packages/issues/2851

**Comment by xiota** [comment]
As far as I can tell, 2024 is the normally licensed version, while NX is the subscription version.  They are both proprietary with a 30-day demo period.

I'm not a fan of distributing proprietary and commercial software, especially when the license does not grant the right to distribute.  In this case, distribution may be implicitly disallowed.  (My understanding is "all rights reserved" = rights not granted are disallowed.)

> All users have the right to:
>
> 1. Make a reasonable number of backup copies for archive purposes, so
long as the backup **copies are not distributed;**
>
> ...
>
> **All rights** of any kind in the Software which are not expressly granted
in this License **are entirely and exclusively reserved** to and by
SoftMaker.

<details><summary>Full text of SoftMaker license.</summary>

**SOFTWARE LICENSE AND WARRANTY**

Read this agreement carefully. If you do not agree to its terms, abort
the installation by clicking the Cancel button.

The software which accompanies this license agreement (the \"Software\")
is the property of SoftMaker Software GmbH (\"SoftMaker\") or its
licensors and is protected by copyright law. While SoftMaker continues
to own the Software, you will have certain rights to use the Software
after your acceptance of this license agreement. Except as may be
modified by a license addendum which accompanies this license agreement,
the following is agreed upon between you and SoftMaker:

**DEFINITIONS**

A. **Non-commercial user:** A licensee who is a natural person and does
not use the Software for for-profit purposes.

B. **Commercial user:** A licensee who is not a natural person and/or
uses the Software for for-profit purposes.

C. **Computer:** A hardware system (either physical or virtual) capable
of running the Software. A blade as part of a blade server, or a
hardware partition is considered a separate Computer. When using the
Software via remote access, the device through which the user interacts
with the Software is considered a Computer.

**GRANT OF RIGHTS TO NON-COMMERCIAL USERS**

If you are a **non-commercial user**, you and members of your family may
install and use one license of the Software on up to **5 (five)
Computers** simultaneously, so long as all of these Computers belong to
the same household.

**GRANT OF RIGHTS TO COMMERCIAL USERS**

If you are a **commercial user**, you may use the Software either under
a **computer license** or under a **user license**:

**A. Computer license**

1\. Each license may only be installed and used on **one (1) Computer**.

2\. Every user of that Computer may use the Software, but only **1 (one)
user** at any given time.

3\. Secondary use right: The single primary user of that Computer is
additionally entitled to use the Software on a portable computer.

**B. User license**

Each license may be installed and used by **one (1) user** on up to five
Computers. The use of the Software by other persons is not permitted.

**TERM OF USAGE**

If you have licensed the Software through a **subscription**, your right
to use the Software is limited to the subscription period. You may have
the option to renew your subscription. If you renew your subscription,
you may continue to use the Software until the end of your extended
subscription period. After the subscription expires, you will not be
able to use the Software.

If you have licensed the Software by **purchasing a permanent license**,
you are entitled to use the licensed version of the Software for an
unlimited period of time.

**LICENSE VERIFICATION**

When the Software is used on a Computer for the first time, and when
certain changes are made to the hardware of a Computer, and in some
license models from time to time, the Software establishes an Internet
connection with a SoftMaker license server to verify the validity of the
license. If you do not have a valid license, the Software cannot be
used.

**ADDITIONAL RIGHTS**

All users have the right to:

1\. Make a reasonable number of backup copies for archive purposes, so
long as the backup copies are not distributed; and

2\. Transfer the usage rights in the Software on a permanent basis to
another person or entity, provided that you retain no copies of the
Software and the transferee agrees to the terms of this agreement;

**YOU MAY NOT:**

1\. Make copies of the accompanying documentation;

2\. Sublicense, rent or lease any portion of the Software or
accompanying documentation; or

3\. Reverse-engineer, decompile, dissassemble, modify, translate, make
any attempt to discover the source code of the Software, or create
derivative works of the Software.

**LIMITED WARRANTY**

TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SOFTMAKER DISCLAIMS
ALL WARRANTIES, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
ANY IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE, AND ALL SUCH WARRANTIES ARE EXPRESSLY AND SPECIFICALLY
DISCLAIMED. NEITHER SOFTMAKER NOR ANYONE ELSE WHO HAS BEEN INVOLVED IN
THE CREATION, PRODUCTION, OR DELIVERY OF THIS SOFTWARE SHALL BE LIABLE
FOR ANY INDIRECT, CONSEQUENTIAL, OR INCIDENTAL DAMAGES ARISING OUT OF
THE USE OR INABILITY TO USE SUCH SOFTWARE EVEN IF SOFTMAKER HAS BEEN
ADVISED OF POSSIBILITY OF SUCH DAMAGES OR CLAIMS. IN NO EVENT SHALL
SOFTMAKER\'S LIABILITY FOR ANY DAMAGES EVER EXCEED THE PRICE PAID FOR
LICENSE TO USE THE SOFTWARE, REGARDLESS OF THE FORM OF QUALITY AND
PERFORMANCE OF THE SOFTWARE. THE PERSON USING THE SOFTWARE BEARS ALL
RISK AS TO THE QUALITY AND PERFORMANCE OF THE SOFTWARE.

**GENERAL**

This Agreement is the complete statement of the Agreement between the
parties on the subject matter, and merges and supersedes all other or
prior understandings, purchase orders, agreements and arrangements. This
Agreement shall be governed by and construed in accordance with the laws
of the Federal Republic of Germany. Exclusive jurisdiction and venue for
all matters relating to this Agreement shall be in courts located in the
City of Nürnberg, Germany, and you consent to such jurisdiction and
venue, thereby excluding the United Nations Convention on Contracts for
the International Sale of Goods and any legislation implementing such
Convention, if otherwise applicable.

If any provision of this Agreement is declared by a court of competent
jurisdiction to be invalid, illegal, or unenforceable, such a provision
shall be severed from the Agreement and the other provisions shall
remain in full force and effect.

All rights of any kind in the Software which are not expressly granted
in this License are entirely and exclusively reserved to and by
SoftMaker.
</details>

**Comment by Technetium1** [comment]
If NX is exclusively for subscription, then it isn't right for us to add this.

**Comment by DeN-AlB** [comment]
> If NX is exclusively for subscription, then it isn't right for us to add this.

Why? What is the difference between the normal, yearly updates version that you have to buy and the subscription version? Both versions you have to buy.

> My understanding is "all rights reserved" = rights not granted are disallowed.

If you look onto their download website, you can see that there are packages for nearly all distributions. Manjaro has the packages in their repos. All other Arch distributions have to install from AUR or with the help of the TGZ-archive.

So why it shouldn't be allowed to distribute the Softmaker packages? So all other packages from Softmaker Office should also be  removed from Chaotic-AUR.

**Comment by Technetium1** [comment]
It is likely to have even less users than `softmaker-office-2024-bin`, which already doesn't have very many. The other half of that is based on the size, since we have limited space on mirrors. `softmaker-office-2024-bin` is `423.29 MiB`, and certainly this would not be significantly smaller. Both versions must be purchased after 30 day trial, you don't have to buy to use it. See the linked issue, I contacted them with questions, expecting an answer when the next couple business days and will update there.

**Comment by xiota** [comment]
When the license doesn't allow distribution, packages should be removed from the repo.  While there can be resistance to removing already available packages, adding new non-compliant packages should be avoided.

I'm not a fan of providing free distribution services to commercial companies for proprietary software that cannot be used by most users.  IMO, they should at least provide a mirror or build server.  Would be nice to have an unlimited trial period or alternate licensing (eg, freemium) for Chaotic AUR users.

**Comment by DeN-AlB** [comment]
> Would be nice to have an unlimited trial period or alternate licensing (eg, freemium) for Chaotic AUR users.

There is a free version of Softmaker Office that everyone could use for free - SoftMaker FreeOffice. You can find it here:
https://www.freeoffice.com/en/

**Comment by xiota** [comment]
Last time I looked at it, it was extremely primitive.  Looks like they updated it.  Would have to check, but it would probably be subject to the same distribution restriction as the demo/paid versions.

**Comment by Technetium1** [comment]
We already provide [freeoffice](https://aur.archlinux.org/packages/freeoffice) and confirmed the same text is in that EULA too
