### ISSUE TITLE
[Request] protontricks

### ISSUE THREAD

**Issue by DeN-AlB** [chaotic-aur/packages#3435]
### Package

https://aur.archlinux.org/packages/protontricks

### Purpose

Simple wrapper that does winetricks things for Proton enabled games.

Package "protontricks-git" is already in Chaotic-AUR, but it seems like package "protontricks" is maintained  more often.

### License

GPL-3.0-or-later

### Submission checklist

- [X] The package is not banned.
- [X] The package is not available in Chaotic AUR or official Arch repos.
- [X] The package has not already been requested.

**Comment by Technetium1** [comment]
`protontricks-git` is always more updated, as the `-git` name implies. It is rebuilt every time upstream git repository changes. That means it has updated 6 times since the last release of `protontricks` per https://github.com/Matoking/protontricks/compare/1.12.0...master

I struggle to imagine a context where you wouldn't want the latest upstream changes for something like this. Are you **sure** you want to request it?

**Comment by DeN-AlB** [comment]
> `protontricks-git` is always more updated, as the `-git` name implies.

I didn't know that. For me it looks like there is a newer version from protontricks package in the AUR, 1.12.0-1. protontricks-git package is on 1.11.1.r8.g3d019ca-3. Or am I getting something wrong?

**Comment by Technetium1** [comment]
Make sure your mirrorlist is correct, it is currently at `1.12.0.r6.ga7319c5-1` which is directly correlates to the latest commit https://github.com/Matoking/protontricks/commit/a7319c57bb476154e9e54e52eb1b8543eef3475a

After typing that out, I realized you're probably reading the pkgver shown on the AUR page rather than querying with pacman. That is not bumped on `-git` packages unless there is some other breaking change to the build process, in which case it will be updated to reflect the latest commit at the time of the change. It always builds the latest commit by design, take a look here: https://wiki.archlinux.org/title/VCS_package_guidelines#VCS_sources

**Comment by xiota** [comment]
@DeN-AlB `-git` packages update pkgver on rebuild.

```
$ pacman -Ss protontricks
chaotic-aur/protontricks-git 1.12.0.r6.ga7319c5-1
    A simple wrapper that does winetricks things for Proton enabled games.
```

**Comment by DeN-AlB** [comment]
> I realized you're probably reading the pkgver shown on the AUR page rather than querying with pacman.

Correct. That's what I did. So, I was wrong filing that request. I'll use the git package now. Thanks. And sorry ...

**Comment by xiota** [comment]
@DeN-AlB No need to apologize.  People who don't regularly build packages don't necessarily know how different package types work.  There can also be reasons to need different package types to be available.
