### ISSUE TITLE
[request] kotatogram-desktop

### ISSUE THREAD

**Issue by xstefen** [chaotic-aur/packages#451]
https://aur.archlinux.org/packages/kotatogram-desktop/

<3

**Comment by dr460nf1r3** [comment]
Checksums dont match, Ive asked the maintainer to fix this

**Comment by xiota** [comment]
Planning to drop this package "soon" because no new release in years and still based on Qt5.  I am current maintainer of AUR package and will disown when it is dropped here.

**Comment by xiota** [comment]
@txtsd Are you interested in taking over maintenance of this or the -git package?  (Asking because you previously commented on aurweb.)  If not, I will disown both packages "soon".

**Comment by txtsd** [comment]
@xiota I don't mind actually. Add me as co-maintainer. Then disown whenever you feel like it. I'll take both.

**Comment by xiota** [comment]
@txtsd Will add you and disown.  `aur/kotatogram-desktop` should be working.  Last build attempt was last week.  `aur/kotatogram-desktop-git` currently failing to build because deprecated macros were removed in Qt6.8.  Have to wait until upstream kotatogram resyncs.  But upstream telegram currently doesn't build because of (I think) some ffmpeg-related issue.  So could be a while.

**Comment by xiota** [comment]
@txtsd `aur/kotatogram-desktop` fails to build with errors: `fatal error: gsl/gsl_assert: No such file or directory`.

The following at end of `prepare()` fixes the missing headers.
```
for i in $(grep -Rln '<gsl/gsl_' "$_pkgsrc"); do
  sed -E -e '/#include/s|<gsl/gsl_([a-z_]+)>|<gsl/\1>|' -i "$i"
done

sed -E -e '1i #include <cstring>' -i "$_pkgsrc/Telegram/lib_tl/tl/tl_basic_types.h"
```

**Comment by txtsd** [comment]
@xiota Thank you. I haven't yet taken a look at the kotatogram packages. Been a little busy.

**Comment by txtsd** [comment]
I got `kotatogram-desktop` building. The -git package is another story.
