### ISSUE TITLE
[Request] telegrand-git / paper-plane-git

### ISSUE THREAD

**Issue by rodrigost23** [chaotic-aur/packages#557]
~~Please add [telegrand-git](https://aur.archlinux.org/packages/telegrand-git/)~~

https://aur.archlinux.org/packages/paper-plane-git

Alternative Telegram client for GNOME desktop.

**Comment by xiota** [comment]
Telegrand project has been renamed to Paper Plane.  Associated PRQs at [aur-requests](https://lists.archlinux.org/archives/search?mlist=aur-requests%40lists.archlinux.org&sort=date-desc&q=telegrand).  However, `paper-plane-git` does not build because of missing `libadwaita-git`.  [paper-plane-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/paper-plane-git.log)

**Comment by xiota** [comment]
Rejecting and closing because `libadwaita-git` is broken.  See #2478
