### ISSUE TITLE
[Request] xemu-git

### ISSUE THREAD

**Issue by NerosTie** [chaotic-aur/packages#610]
original xbox emulator
https://aur.archlinux.org/packages/xemu-git/

https://github.com/mborgerson/xemu

**Comment by dr460nf1r3** [comment]
This one is already present in the repo?

**Comment by NerosTie** [comment]
xemu in Chaotic is outdated (v0.7.117 < v0.7.118) + there is an up-to-date package named "xemu-bin" in AUR. Maybe xemu-git can be removed from Chaotic repo?

**Comment by Technetium1** [comment]
Since the release of https://github.com/xemu-project/xemu/releases/tag/v0.7.118 it's not building, I've [flagged the package](https://aur.archlinux.org/pkgbase/xemu-git/flag-comment) out of date, and the maintainer should update it soon.
Here's a log of the failure to patch: [xemu-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/xemu-git.log)
