### ISSUE TITLE
CliFM is broken

### ISSUE THREAD

**Issue by leo-arch** [chaotic-aur/packages#659]
Thank you very much for having added CliFM  to your repo (the author here). But, sadly, while the package installs fine from the AUR, or manually, it is broken when installed from chaotic (`Illegal instruction (core dumped)`).

Thanks again.

**Comment by PedroHLC** [comment]
Yeah, the AUR maintainer added "-march=native" in the script, that must be adding AVX2 to it. Thanks for notifying us, we'll take care of this.

**Comment by PedroHLC** [comment]
Fixed in https://github.com/chaotic-aur/interfere/commit/d3527c52d4731e51ead363f6d7ee13896d899286.
I've also added it globally in https://github.com/chaotic-aur/toolbox/commit/a1672ba043dc11d0d55a361e70c8b7ed2f77cfc2. So as soon as we update all builders I can remove the package-specific one.

Thanks for your collaboration and software.

**Comment by leo-arch** [comment]
Thanks @PedroHLC! Btw, great job with chaotic. Thanks for that too.
