### ISSUE TITLE
[request] freecad-git

### ISSUE THREAD

**Issue by adrianinsaval** [chaotic-aur/packages#774]
Hi! is it possible to get freecad-git built daily?
AUR:  https://aur.archlinux.org/packages/freecad-git/
note that check() might fail every now and then when bugs are introduced in freecad's master branch or the built-in tests are not update for new features

**Comment by dr460nf1r3** [comment]
We could remove the check in this case 👀

**Comment by adrianinsaval** [comment]
thanks! @dr460nf1r3 that would be best IMO, I don't believe that check should be in the PKGBUILD to begin with, it's a development version after all, it's expected that it won't remain working the same.

**Comment by dr460nf1r3** [comment]
Done! :)

**Comment by xiota** [comment]
Switched to a custom package because interfere to keep buildable has grown increasingly complicated.  Can switch back to AUR with minimal interfere when it's updated.  Metrics 227.

@adrianinsaval You appear to be comaintainer of the AUR package.  Feel free to use as reference: https://github.com/chaotic-aur/packages/blob/main/freecad-git
