### ISSUE TITLE
quassel

### ISSUE THREAD

**Issue by ahmubashshir** [chaotic-aur/packages#802]
https://aur.archlinux.org/pkgbase/quassel/

**Comment by xiota** [comment]
Dropping this because of issues:

* Has broken a few times.  Currently broken from missing makedepends.  While maintainer has fixed major issues upon notice, this package is annoying to work with.
* Uses `quassel` pkgbase instead of `quassel-git`.  Makes bumps and rebuilding more complicated.
* Rebuilds the same package multiple times.  Wastes time and resources when only a few of the sub-packages are broken.  They should each be their own package or have some mechanism to selectively build.

If someone really needs this, please comment to explain why it's worth keeping.

Metrics:
```
quassel-client-git 6
quassel-client-light-git 6
quassel-client-light-webengine-git 7
quassel-common-git 8
quassel-core-git 6
quassel-git 6
quassel-light-git 7
quassel-light-webengine-git 6
```
