### ISSUE TITLE
 [Request] qv2ray

### ISSUE THREAD

**Issue by The-0Day** [chaotic-aur/packages#893]
- Link to the package(s) in AUR: [qv2ray](https://aur.archlinux.org/packages/qv2ray/)

- Utility this package has for you:

It allows me to Combine it with Proxychains4 and have a good, fast VPN connection.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [x] YES
  - [ ] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by Technetium1** [comment]
This project has been [deprecated](https://qv2ray.net/Deprecation-Notice/) as of the [last release](https://github.com/Qv2ray/Qv2ray/releases/tag/v2.7.0). It's safe to say there will not be any future updates, as the only commit since then was an April fools joke about future development https://github.com/Qv2ray/Qv2ray/commit/844f79ae6c797f82a07a19aca6ace35f637d9515. Likewise there have been no updates to the package on the [AUR](https://aur.archlinux.org/cgit/aur.git/log/?h=qv2ray).
