### ISSUE TITLE
[Request] openblas-lapack

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#927]
## 👶 For requesting new packages

- Link to the package(s) in AUR: [https://aur.archlinux.org/packages/openblas-lapack/](openblas-lapack)

- Utility this package has for you:

 It is an alternative implementation for blas/lapack, and it is necessary for some packages (example, qiskit) to work, as opposed to the blas/lapack packages in official repos.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by xiota** [comment]
Dropped because provided by `extra/blas-openblas`.  Metrics 2.

**Comment by xiota** [comment]
There have been reports of a performance difference between `extra/blas-openblas` and `aur/openblas-lapack`.  After testing, the difference appears to be caused by `march=x86-64` vs `march=native`.  The difference on my computer is slight, about 12%, much less than reported elsewhere.

Packages built with `march=native` are unsuitable for inclusion in binary repos because of potential illegal instruction errors.  Further, the `extra` package has a `replaces` directive, which causes the `aur` package to be uninstalled whenever the system is updated, preventing it from being used without significant inconvenience.

Users who need better performance may rebuild [`extra/openblas`](https://archlinux.org/packages/extra/x86_64/openblas/) after editing `/etc/makepkg.conf`.  They may also consider using the packages matching their architecture, provided by [CachyOS](https://wiki.cachyos.org/features/optimized_repos/).
