### ISSUE TITLE
[Broken] Needs repair Ungoogled-Chromium

### ISSUE THREAD

**Issue by qx-775** [chaotic-aur/packages#958]
Ungoogled-chromium is currently broken on your infra and won't compile (see the [link])(https://builds.garudalinux.org/repos/chaotic-aur/logs/ungoogled-chromium-archlinux.log) 

Version 93 has been out for a few days with lots of security fixes, however chaotic AUR only has version 92.

> (If available) Link to latest build ([find it here](https://builds.garudalinux.org/repos/chaotic-aur/logs/)): [some-package.log]

https://builds.garudalinux.org/repos/chaotic-aur/logs/ungoogled-chromium-archlinux.log

- Package name: `ungoogled-chromium`

- Latest build: `93.0.4577.82-1`

- Latest version available: `92.0.4515.159`

- Have you tested if the latest version of the package builds in a clean chroot?:
  - NO

Could someone take a look at what goes wrong?
Btw, I absolutely love that I can view the logs of your server infrastructure. Amazing feature.

**Comment by dr460nf1r3** [comment]
I'm aware of it and tried to rebuilt yesterday already. The AUR version seems to be broken due to a recent harfbuzz update (won't compile). I tried building from here instead the [official Ungoogled Chromium repo](https://github.com/ungoogled-software/ungoogled-chromium-archlinux.git) when the builder apparently ran out of space.
